# Generated by Django 4.2.7 on 2025-06-30 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0003_contractsignature_biometric_data_and_more'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('rent_payment', 'Pago de Renta'), ('monthly_rent', 'Renta Mensual'), ('security_deposit', 'Depósito de Garantía'), ('service_payment', 'Pago de Servicios'), ('utilities', 'Servicios Públicos'), ('parking_fee', 'Cuota de Estacionamiento'), ('pet_deposit', 'Depósito por Mascota'), ('rent_increase', 'Aumento de Renta'), ('commission', 'Comisión'), ('refund', 'Reembolso'), ('penalty', 'Penalización'), ('late_fee', 'Recargo por Mora'), ('maintenance_fee', 'Cuota de Mantenimiento'), ('repair_cost', 'Costo de Reparación'), ('cleaning_fee', 'Tarifa de Limpieza'), ('platform_fee', 'Comisión de Plataforma'), ('escrow_deposit', 'Depósito en Escrow'), ('escrow_release', 'Liberación de Escrow')], max_length=20, verbose_name='Tipo de transacción'),
        ),
        migrations.CreateModel(
            name='RentPaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de renta')),
                ('due_date', models.PositiveIntegerField(default=1, verbose_name='Día de vencimiento')),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Recargo por mora')),
                ('grace_period_days', models.PositiveIntegerField(default=5, verbose_name='Días de gracia')),
                ('auto_charge_enabled', models.BooleanField(default=False, verbose_name='Cobro automático habilitado')),
                ('auto_late_fee_enabled', models.BooleanField(default=True, verbose_name='Recargo automático por mora')),
                ('reminder_days_before', models.PositiveIntegerField(default=3, verbose_name='Días de recordatorio antes')),
                ('send_payment_confirmations', models.BooleanField(default=True, verbose_name='Enviar confirmaciones de pago')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='Última fecha de pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rent_schedule', to='contracts.contract', verbose_name='Contrato')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_rent_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Arrendador')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentmethod', verbose_name='Método de pago automático')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Arrendatario')),
            ],
            options={
                'verbose_name': 'Cronograma de Pago de Renta',
                'verbose_name_plural': 'Cronogramas de Pago de Renta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentPaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('upcoming', 'Próximo Vencimiento'), ('due_today', 'Vence Hoy'), ('overdue', 'Vencido'), ('late_fee_applied', 'Recargo Aplicado')], max_length=20, verbose_name='Tipo de recordatorio')),
                ('due_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto adeudado')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado el')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Enviado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='payments.rentpaymentschedule', verbose_name='Cronograma')),
            ],
            options={
                'verbose_name': 'Recordatorio de Pago',
                'verbose_name_plural': 'Recordatorios de Pago',
                'ordering': ['-created_at'],
            },
        ),
    ]
