# Generated by Django 4.2.7 on 2025-07-21 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0003_colombiancontract_legalclause_contractmilestone_and_more'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractEscrowAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_deposited', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('held_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('released_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('auto_release_enabled', models.BooleanField(default=True)),
                ('hold_period_hours', models.IntegerField(default=24, help_text='Horas antes de liberación automática')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('FROZEN', 'Congelado'), ('DISPUTE', 'En Disputa'), ('CLOSED', 'Cerrado')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_account', to='contracts.colombiancontract')),
            ],
            options={
                'db_table': 'escrow_accounts',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='escrow_milestone_id',
            field=models.CharField(blank=True, help_text='ID del hito de escrow que esta transacción libera', max_length=100, verbose_name='ID de Hito de Escrow'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='escrow_reference',
            field=models.CharField(blank=True, help_text='ID de la cuenta de escrow relacionada con contratos', max_length=100, verbose_name='Referencia de Escrow'),
        ),
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Depósito'), ('HOLD', 'Retención'), ('RELEASE', 'Liberación'), ('REFUND', 'Reembolso'), ('FEE', 'Comisión')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_escrow_transactions', to=settings.AUTH_USER_MODEL)),
                ('escrow_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.contractescrowaccount')),
                ('related_milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contractmilestone')),
            ],
            options={
                'db_table': 'escrow_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowReleaseRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('TIME_BASED', 'Basado en Tiempo'), ('MILESTONE_BASED', 'Basado en Hitos'), ('APPROVAL_BASED', 'Basado en Aprobación'), ('AUTOMATED', 'Completamente Automático')], max_length=30)),
                ('conditions', models.JSONField(default=dict)),
                ('actions', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('escrow_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_rules', to='payments.contractescrowaccount')),
            ],
            options={
                'db_table': 'escrow_release_rules',
                'ordering': ['priority'],
            },
        ),
    ]
