# Generated by Django 4.2.7 on 2026-04-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_contractescrowaccount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="escrowaccount",
            name="currency",
            field=models.CharField(default="COP", max_length=3, verbose_name="Moneda"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="currency",
            field=models.CharField(default="COP", max_length=3, verbose_name="Moneda"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="currency",
            field=models.CharField(default="COP", max_length=3, verbose_name="Moneda"),
        ),
    ]
