# Generated by Django 4.2.7 on 2026-04-16 13:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "payments",
            "0004_alter_escrowaccount_currency_alter_invoice_currency_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalInterestRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                        ],
                        verbose_name="Mes",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Año")),
                (
                    "monthly_rate",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=6,
                        verbose_name="Tasa mensual (decimal, ej. 0.0208 = 2.08%)",
                    ),
                ),
                (
                    "max_usury_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0208"),
                        max_digits=6,
                        verbose_name="Tope de usura mensual vigente al momento del registro",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Resolución SFC-XXXX-2026, Banco de la República",
                        max_length=200,
                        verbose_name="Fuente / certificación",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tasa de Interés Legal",
                "verbose_name_plural": "Tasas de Interés Legal",
                "ordering": ["-year", "-month"],
                "indexes": [
                    models.Index(
                        fields=["year", "month"], name="payments_le_year_033cff_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="payments_le_is_acti_d1293d_idx"
                    ),
                ],
                "unique_together": {("month", "year")},
            },
        ),
    ]
