# Generated by Django 4.2.7 on 2026-04-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0006_seed_legal_interest_rates"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentpaymentschedule",
            name="legal_grace_days_max",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Cap legal de días para los que se calcula interés moratorio.",
                verbose_name="Días máximos de mora computables",
            ),
        ),
        migrations.AlterField(
            model_name="rentpaymentschedule",
            name="late_fee_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Recargo por mora (legacy/fallback)",
            ),
        ),
    ]
