# Generated by Django 4.2.7 on 2026-04-16 13:24

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0007_rentpaymentschedule_legal_grace_days_max_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        db_index=True,
                        help_text="Formato PO-YYYY-NNNNNNNN, generado automáticamente.",
                        max_length=30,
                        unique=True,
                        verbose_name="Número consecutivo",
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("rent", "Canon de arrendamiento"),
                            ("service", "Servicio prestado"),
                            ("subscription", "Suscripción de plataforma"),
                            ("deposit", "Depósito / garantía"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de orden",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("partial", "Pagada parcialmente"),
                            ("paid", "Pagada"),
                            ("overdue", "En mora"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto base"
                    ),
                ),
                (
                    "interest_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Intereses moratorios acumulados",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Monto pagado",
                    ),
                ),
                ("date_due", models.DateField(verbose_name="Fecha de vencimiento")),
                (
                    "date_grace_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fin de período de gracia"
                    ),
                ),
                (
                    "date_max_overdue",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tope legal de mora"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descripción"
                    ),
                ),
                (
                    "audit_log",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Log de eventos"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_orders_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creada por",
                    ),
                ),
                (
                    "installment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_orders",
                        to="payments.paymentinstallment",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_orders",
                        to="payments.invoice",
                    ),
                ),
                (
                    "payee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_orders_to_receive",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Beneficiario",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_orders_to_pay",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pagador",
                    ),
                ),
                (
                    "rent_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_orders",
                        to="payments.rentpaymentschedule",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Transaction de la pasarela cuando se completa el pago.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_orders",
                        to="payments.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Pago",
                "verbose_name_plural": "Órdenes de Pago",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order_number"], name="payments_pa_order_n_0698ad_idx"
                    ),
                    models.Index(
                        fields=["order_type", "status"],
                        name="payments_pa_order_t_2fda35_idx",
                    ),
                    models.Index(
                        fields=["payer", "status"],
                        name="payments_pa_payer_i_4fa85a_idx",
                    ),
                    models.Index(
                        fields=["payee", "status"],
                        name="payments_pa_payee_i_a09e51_idx",
                    ),
                    models.Index(
                        fields=["date_due"], name="payments_pa_date_du_1f2a5e_idx"
                    ),
                ],
            },
        ),
    ]
