# Generated by Django 4.2.24 on 2026-05-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_paymentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadatos'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
    ]
