# Generated by Django 4.2.7 on 2025-06-28 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('nationality', models.CharField(default='Mexicana', max_length=100, verbose_name='Nacionalidad')),
                ('marital_status', models.CharField(blank=True, max_length=50, verbose_name='Estado civil')),
                ('dependents', models.PositiveIntegerField(default=0, verbose_name='Número de dependientes')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, verbose_name='Contacto de emergencia')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, verbose_name='Teléfono de emergencia')),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=100, verbose_name='Relación')),
                ('emergency_contact_address', models.CharField(blank=True, max_length=255, verbose_name='Dirección de emergencia')),
                ('education_level', models.CharField(blank=True, choices=[('primary', 'Primaria'), ('secondary', 'Secundaria'), ('high_school', 'Preparatoria'), ('bachelor', 'Licenciatura'), ('master', 'Maestría'), ('doctorate', 'Doctorado'), ('technical', 'Técnico'), ('other', 'Otro')], max_length=20, verbose_name='Nivel educativo')),
                ('institution_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre de la institución')),
                ('field_of_study', models.CharField(blank=True, max_length=200, verbose_name='Campo de estudio')),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de graduación')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Promedio')),
                ('current_employer', models.CharField(blank=True, max_length=200, verbose_name='Empleador actual')),
                ('current_position', models.CharField(blank=True, max_length=200, verbose_name='Cargo actual')),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Tiempo completo'), ('part_time', 'Tiempo parcial'), ('contract', 'Por contrato'), ('freelance', 'Freelance'), ('temporary', 'Temporal'), ('internship', 'Pasante'), ('self_employed', 'Trabajador independiente')], max_length=20, verbose_name='Tipo de empleo')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salario mensual')),
                ('supervisor_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del supervisor')),
                ('supervisor_phone', models.CharField(blank=True, max_length=15, verbose_name='Teléfono del supervisor')),
                ('supervisor_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del supervisor')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del banco')),
                ('account_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de cuenta')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Número de cuenta')),
                ('credit_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Puntuación crediticia')),
                ('monthly_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Gastos mensuales')),
                ('reference1_name', models.CharField(blank=True, max_length=200, verbose_name='Referencia 1 - Nombre')),
                ('reference1_phone', models.CharField(blank=True, max_length=15, verbose_name='Referencia 1 - Teléfono')),
                ('reference1_email', models.EmailField(blank=True, max_length=254, verbose_name='Referencia 1 - Email')),
                ('reference1_relation', models.CharField(blank=True, max_length=100, verbose_name='Referencia 1 - Relación')),
                ('reference2_name', models.CharField(blank=True, max_length=200, verbose_name='Referencia 2 - Nombre')),
                ('reference2_phone', models.CharField(blank=True, max_length=15, verbose_name='Referencia 2 - Teléfono')),
                ('reference2_email', models.EmailField(blank=True, max_length=254, verbose_name='Referencia 2 - Email')),
                ('reference2_relation', models.CharField(blank=True, max_length=100, verbose_name='Referencia 2 - Relación')),
                ('previous_addresses', models.JSONField(blank=True, default=list, verbose_name='Direcciones anteriores')),
                ('eviction_history', models.BooleanField(default=False, verbose_name='Historial de desalojo')),
                ('eviction_details', models.TextField(blank=True, verbose_name='Detalles de desalojo')),
                ('rental_history', models.JSONField(blank=True, default=list, verbose_name='Historial de rentas')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='resume/id/', verbose_name='Documento de identificación')),
                ('id_document_status', models.CharField(choices=[('pending', 'Pendiente'), ('verified', 'Verificado'), ('rejected', 'Rechazado'), ('expired', 'Expirado')], default='pending', max_length=20, verbose_name='Estado del documento de ID')),
                ('proof_of_income', models.FileField(blank=True, null=True, upload_to='resume/income/', verbose_name='Comprobante de ingresos')),
                ('proof_of_income_status', models.CharField(choices=[('pending', 'Pendiente'), ('verified', 'Verificado'), ('rejected', 'Rechazado'), ('expired', 'Expirado')], default='pending', max_length=20, verbose_name='Estado del comprobante de ingresos')),
                ('bank_statement', models.FileField(blank=True, null=True, upload_to='resume/bank/', verbose_name='Estado de cuenta bancario')),
                ('bank_statement_status', models.CharField(choices=[('pending', 'Pendiente'), ('verified', 'Verificado'), ('rejected', 'Rechazado'), ('expired', 'Expirado')], default='pending', max_length=20, verbose_name='Estado del estado de cuenta')),
                ('employment_letter', models.FileField(blank=True, null=True, upload_to='resume/employment/', verbose_name='Carta laboral')),
                ('employment_letter_status', models.CharField(choices=[('pending', 'Pendiente'), ('verified', 'Verificado'), ('rejected', 'Rechazado'), ('expired', 'Expirado')], default='pending', max_length=20, verbose_name='Estado de la carta laboral')),
                ('tax_return', models.FileField(blank=True, null=True, upload_to='resume/tax/', verbose_name='Declaración de impuestos')),
                ('tax_return_status', models.CharField(choices=[('pending', 'Pendiente'), ('verified', 'Verificado'), ('rejected', 'Rechazado'), ('expired', 'Expirado')], default='pending', max_length=20, verbose_name='Estado de la declaración de impuestos')),
                ('credit_report', models.FileField(blank=True, null=True, upload_to='resume/credit/', verbose_name='Reporte crediticio')),
                ('credit_report_status', models.CharField(choices=[('pending', 'Pendiente'), ('verified', 'Verificado'), ('rejected', 'Rechazado'), ('expired', 'Expirado')], default='pending', max_length=20, verbose_name='Estado del reporte crediticio')),
                ('criminal_record', models.BooleanField(default=False, verbose_name='Antecedentes penales')),
                ('criminal_record_details', models.TextField(blank=True, verbose_name='Detalles de antecedentes penales')),
                ('criminal_record_document', models.FileField(blank=True, null=True, upload_to='resume/criminal/', verbose_name='Documento de antecedentes penales')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Hoja de vida completa')),
                ('verification_score', models.PositiveIntegerField(default=0, verbose_name='Puntuación de verificación')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Notas de verificación')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hoja de Vida',
                'verbose_name_plural': 'Hojas de Vida',
            },
        ),
    ]
