# Generated by Django 4.2.7 on 2025-07-06 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewcode',
            name='interview_rating',
            field=models.PositiveSmallIntegerField(default=5, help_text='Calificación de 1 a 10 basada en la entrevista', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Calificación de entrevista'),
        ),
    ]
