# Generated by Django 5.2.3 on 2025-06-16 04:05

import django.core.validators
import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=users.models.generate_interview_code, max_length=8, unique=True, verbose_name='Código de entrevista')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilizado')),
                ('initial_rating', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Calificación inicial')),
                ('notes', models.TextField(blank=True, verbose_name='Notas de entrevista')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
            ],
            options={
                'verbose_name': 'Código de Entrevista',
                'verbose_name_plural': 'Códigos de Entrevista',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='initial_rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Calificación inicial'),
        ),
        migrations.AddField(
            model_name='user',
            name='interview_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='users.interviewcode'),
        ),
    ]
