# Generated by Django 4.2.7 on 2025-07-06 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_interviewcode_interview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewcode',
            name='interview_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Calificación de 0 a 10 estrellas basada en la entrevista', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Calificación de entrevista'),
        ),
    ]
