# Generated by Django 4.2.7 on 2025-06-29 01:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='México', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='user',
            name='employer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del empleador'),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('employed', 'Empleado'), ('self_employed', 'Trabajador Independiente'), ('student', 'Estudiante'), ('unemployed', 'Desempleado'), ('retired', 'Jubilado')], max_length=20, null=True, verbose_name='Estado laboral'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Femenino'), ('other', 'Otro'), ('prefer_not_to_say', 'Prefiero no decir')], max_length=20, null=True, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Soltero/a'), ('married', 'Casado/a'), ('divorced', 'Divorciado/a'), ('widowed', 'Viudo/a'), ('other', 'Otro')], max_length=20, null=True, verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_consent',
            field=models.BooleanField(default=False, verbose_name='Consentimiento de marketing'),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ingresos mensuales'),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(default='Mexicana', max_length=100, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('referral', 'Recomendación'), ('advertisement', 'Anuncio'), ('other', 'Otro')], max_length=20, null=True, verbose_name='Fuente de registro'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estado/Provincia'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='user',
            name='years_employed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Años de empleo'),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notificaciones por Email')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='Notificaciones por SMS')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Notificaciones Push')),
                ('newsletter', models.BooleanField(default=True, verbose_name='Newsletter')),
                ('property_alerts', models.BooleanField(default=True, verbose_name='Alertas de Propiedades')),
                ('message_notifications', models.BooleanField(default=True, verbose_name='Notificaciones de Mensajes')),
                ('payment_reminders', models.BooleanField(default=True, verbose_name='Recordatorios de Pagos')),
                ('profile_visibility', models.CharField(choices=[('public', 'Público'), ('private', 'Privado'), ('contacts_only', 'Solo Contactos')], default='public', max_length=20, verbose_name='Visibilidad del Perfil')),
                ('show_contact_info', models.BooleanField(default=True, verbose_name='Mostrar Información de Contacto')),
                ('show_property_history', models.BooleanField(default=False, verbose_name='Mostrar Historial de Propiedades')),
                ('allow_messages', models.BooleanField(default=True, verbose_name='Permitir Mensajes')),
                ('language', models.CharField(default='es', max_length=10, verbose_name='Idioma')),
                ('timezone', models.CharField(default='America/Bogota', max_length=50, verbose_name='Zona Horaria')),
                ('currency', models.CharField(default='COP', max_length=3, verbose_name='Moneda')),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20, verbose_name='Formato de Fecha')),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('auto', 'Automático')], default='light', max_length=10, verbose_name='Tema')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='Autenticación de Dos Factores')),
                ('login_notifications', models.BooleanField(default=True, verbose_name='Notificaciones de Inicio de Sesión')),
                ('session_timeout', models.PositiveIntegerField(default=30, verbose_name='Tiempo de Sesión (minutos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Usuario',
                'verbose_name_plural': 'Configuraciones de Usuario',
            },
        ),
    ]
