# Generated by Django 4.2.7 on 2025-07-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_interviewcode_interview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='budget_range',
            field=models.CharField(choices=[('low', 'Económico'), ('medium', 'Medio'), ('high', 'Alto'), ('luxury', 'Premium')], default='medium', max_length=20, verbose_name='Rango de presupuesto'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del negocio'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre de la empresa'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_address',
            field=models.TextField(blank=True, verbose_name='Dirección actual'),
        ),
        migrations.AddField(
            model_name='user',
            name='family_size',
            field=models.PositiveIntegerField(default=1, verbose_name='Tamaño de familia'),
        ),
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarifa por hora'),
        ),
        migrations.AddField(
            model_name='user',
            name='hourly_rate_currency',
            field=models.CharField(choices=[('COP', 'Pesos Colombianos'), ('USD', 'Dólares Americanos')], default='COP', max_length=3, verbose_name='Moneda de tarifa'),
        ),
        migrations.AddField(
            model_name='user',
            name='move_in_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha deseada de ingreso'),
        ),
        migrations.AddField(
            model_name='user',
            name='pets',
            field=models.BooleanField(default=False, verbose_name='Tiene mascotas'),
        ),
        migrations.AddField(
            model_name='user',
            name='rental_history',
            field=models.BooleanField(default=False, verbose_name='Historial de arrendamiento'),
        ),
        migrations.AddField(
            model_name='user',
            name='service_category',
            field=models.CharField(blank=True, choices=[('maintenance', 'Mantenimiento'), ('cleaning', 'Limpieza'), ('security', 'Seguridad'), ('gardening', 'Jardinería'), ('electrical', 'Electricidad'), ('plumbing', 'Plomería'), ('painting', 'Pintura'), ('moving', 'Mudanzas'), ('other', 'Otro')], max_length=50, verbose_name='Categoría de servicio'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_properties',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de propiedades'),
        ),
        migrations.AddField(
            model_name='user',
            name='years_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Años de experiencia'),
        ),
    ]
