# Generated by Django 4.2.7 on 2025-06-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_city_user_country_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='currency',
            field=models.CharField(choices=[('COP', 'Pesos Colombianos'), ('USD', 'Dólares Americanos')], default='COP', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('COP', 'Pesos Colombianos'), ('USD', 'Dólares Americanos')], default='COP', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='landlordprofile',
            name='country',
            field=models.CharField(default='Colombia', max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='country',
            field=models.CharField(default='Colombia', max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='country',
            field=models.CharField(default='Colombia', max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='Colombia', max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(default='Colombiana', max_length=100, verbose_name='Nacionalidad'),
        ),
    ]
