# Generated by Django 4.2.7 on 2025-07-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_budget_range_user_business_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='source',
            field=models.CharField(blank=True, choices=[('direct', 'Directo'), ('google', 'Google'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('referral', 'Recomendación'), ('advertisement', 'Anuncio'), ('other', 'Otro')], default='direct', max_length=20, null=True, verbose_name='Fuente de registro'),
        ),
    ]
