# Generated by Django 4.2.7 on 2025-06-30 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_contactrequest_interviewcode_interviewsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interview_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='users.interviewcode'),
        ),
    ]
