# Generated by Django 4.2.7 on 2026-03-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_online",
            field=models.BooleanField(default=False, verbose_name="En línea"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_seen",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Última actividad"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="status_mode",
            field=models.CharField(
                choices=[
                    ("online", "En línea"),
                    ("busy", "Ocupado"),
                    ("offline", "Desconectado"),
                ],
                default="offline",
                max_length=10,
                verbose_name="Estado",
            ),
        ),
    ]
