# Generated by Django 4.2.7 on 2025-07-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_interview_code_delete_oldinterviewcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OldInterviewCode',
        ),
    ]
