# Generated by Django 4.2.7 on 2025-07-06 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_oldinterviewcode'),
    ]

    operations = [
    ]
