# Generated by Django 4.2.7 on 2026-03-23 22:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("properties", "0009_alter_propertyvideo_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agent_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Código de agente",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("residential", "Residencial"),
                            ("commercial", "Comercial"),
                            ("both", "Residencial y Comercial"),
                        ],
                        default="both",
                        max_length=30,
                        verbose_name="Especialización",
                    ),
                ),
                (
                    "service_areas",
                    models.JSONField(
                        default=list,
                        help_text="Lista de barrios/zonas que cubre",
                        verbose_name="Zonas de cobertura",
                    ),
                ),
                (
                    "certifications",
                    models.JSONField(
                        default=list,
                        help_text="Certificaciones profesionales del agente",
                        verbose_name="Certificaciones",
                    ),
                ),
                (
                    "max_weekly_visits",
                    models.PositiveIntegerField(
                        default=15, verbose_name="Máximo visitas/semana"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Disponible"),
                ),
                (
                    "availability_notes",
                    models.TextField(
                        blank=True, verbose_name="Notas de disponibilidad"
                    ),
                ),
                (
                    "total_visits_completed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total visitas completadas"
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Calificación promedio",
                    ),
                ),
                (
                    "hired_at",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de contratación",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"is_staff": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agente de Verificación",
                "verbose_name_plural": "Agentes de Verificación",
                "ordering": ["-total_visits_completed"],
            },
        ),
        migrations.CreateModel(
            name="VerificationVisit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "visit_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Número de visita",
                    ),
                ),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("landlord", "Verificación de Arrendador"),
                            ("tenant", "Verificación de Arrendatario"),
                            ("property", "Verificación de Propiedad"),
                            (
                                "service_provider",
                                "Verificación de Prestador de Servicios",
                            ),
                        ],
                        max_length=20,
                        verbose_name="Tipo de visita",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente de Asignación"),
                            ("scheduled", "Programada"),
                            ("in_progress", "En Progreso"),
                            ("completed", "Completada"),
                            ("cancelled", "Cancelada"),
                            ("rescheduled", "Reprogramada"),
                            ("no_show", "No Asistió"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha programada"
                    ),
                ),
                (
                    "scheduled_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora programada"
                    ),
                ),
                (
                    "visit_address",
                    models.TextField(verbose_name="Dirección de la visita"),
                ),
                (
                    "visit_city",
                    models.CharField(
                        default="Bucaramanga", max_length=100, verbose_name="Ciudad"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Hora de inicio real"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Hora de finalización"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Duración (minutos)"
                    ),
                ),
                (
                    "agent_notes",
                    models.TextField(blank=True, verbose_name="Notas del agente"),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="Motivo de cancelación"),
                ),
                (
                    "verification_passed",
                    models.BooleanField(
                        null=True, verbose_name="Verificación aprobada"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_visits",
                        to="verification.verificationagent",
                        verbose_name="Agente asignado",
                    ),
                ),
                (
                    "property_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_visits",
                        to="properties.property",
                        verbose_name="Propiedad a verificar",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_visits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Persona a verificar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visita de Verificación",
                "verbose_name_plural": "Visitas de Verificación",
                "ordering": ["-scheduled_date", "-scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="VerificationReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overall_condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excelente"),
                            ("good", "Bueno"),
                            ("acceptable", "Aceptable"),
                            ("needs_improvement", "Necesita Mejoras"),
                            ("rejected", "Rechazado"),
                        ],
                        max_length=20,
                        verbose_name="Estado general",
                    ),
                ),
                (
                    "initial_rating",
                    models.PositiveSmallIntegerField(
                        help_text="Calificación de 1 a 10 asignada por el agente",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Calificación inicial",
                    ),
                ),
                (
                    "identity_verified",
                    models.BooleanField(
                        default=False, verbose_name="Identidad verificada"
                    ),
                ),
                (
                    "document_type_verified",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Tipo de documento"
                    ),
                ),
                (
                    "document_number_verified",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Número de documento"
                    ),
                ),
                (
                    "property_exists",
                    models.BooleanField(
                        null=True, verbose_name="Propiedad existe físicamente"
                    ),
                ),
                (
                    "property_matches_description",
                    models.BooleanField(
                        null=True, verbose_name="Coincide con descripción"
                    ),
                ),
                (
                    "property_condition_notes",
                    models.TextField(
                        blank=True, verbose_name="Observaciones del inmueble"
                    ),
                ),
                (
                    "person_lives_at_address",
                    models.BooleanField(
                        null=True, verbose_name="Persona vive en la dirección"
                    ),
                ),
                (
                    "person_cooperative",
                    models.BooleanField(
                        default=True, verbose_name="Persona cooperativa"
                    ),
                ),
                (
                    "references_verified",
                    models.BooleanField(
                        default=False, verbose_name="Referencias verificadas"
                    ),
                ),
                ("findings", models.TextField(verbose_name="Hallazgos principales")),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="Recomendaciones"),
                ),
                (
                    "risk_flags",
                    models.JSONField(
                        default=list,
                        help_text="Lista de alertas identificadas durante la verificación",
                        verbose_name="Alertas de riesgo",
                    ),
                ),
                (
                    "photo_evidence",
                    models.JSONField(
                        default=list,
                        help_text="URLs de fotos tomadas durante la visita",
                        verbose_name="Evidencias fotográficas",
                    ),
                ),
                (
                    "approved_by_admin",
                    models.BooleanField(
                        default=False, verbose_name="Aprobado por admin"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, verbose_name="Notas del administrador"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha del reporte"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="verification.verificationvisit",
                        verbose_name="Visita asociada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte de Verificación",
                "verbose_name_plural": "Reportes de Verificación",
                "ordering": ["-created_at"],
            },
        ),
    ]
