# Generated by Django 4.2.7 on 2026-04-26 00:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid
import verification.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("verification", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldVisitRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type_declared",
                    models.CharField(
                        choices=[
                            ("cedula_ciudadania", "Cédula de Ciudadanía"),
                            ("cedula_extranjeria", "Cédula de Extranjería"),
                            ("tarjeta_identidad", "Tarjeta de Identidad"),
                            ("pasaporte", "Pasaporte"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de documento declarado",
                    ),
                ),
                (
                    "document_number_declared",
                    models.CharField(
                        max_length=30, verbose_name="Número de documento declarado"
                    ),
                ),
                (
                    "full_name_declared",
                    models.CharField(
                        max_length=200, verbose_name="Nombre completo declarado"
                    ),
                ),
                (
                    "cedula_anverso",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=verification.models._field_visit_upload_path,
                        verbose_name="Cédula anverso",
                    ),
                ),
                (
                    "cedula_reverso",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=verification.models._field_visit_upload_path,
                        verbose_name="Cédula reverso",
                    ),
                ),
                (
                    "selfie_liveness",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=verification.models._field_visit_upload_path,
                        verbose_name="Selfie con liveness",
                    ),
                ),
                (
                    "ocr_data",
                    models.JSONField(
                        blank=True,
                        help_text="ParsedColombianID: número, nombres, apellidos, fechas",
                        null=True,
                        verbose_name="Datos OCR",
                    ),
                ),
                (
                    "liveness_data",
                    models.JSONField(
                        blank=True,
                        help_text="LivenessResult sin imagen (head turns + métricas)",
                        null=True,
                        verbose_name="Datos liveness",
                    ),
                ),
                (
                    "face_match_data",
                    models.JSONField(
                        blank=True,
                        help_text="FaceMatchResult cédula↔selfie (similarity + threshold)",
                        null=True,
                        verbose_name="Match facial",
                    ),
                ),
                (
                    "digital_score",
                    models.JSONField(
                        help_text="VerihomeIdScoreBreakdown con sub-puntajes y observaciones",
                        verbose_name="Score digital desglosado",
                    ),
                ),
                (
                    "digital_score_total",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Score parcial 0.0–0.5 (la visita en campo aporta el resto)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(0.5),
                        ],
                        verbose_name="Score digital total",
                    ),
                ),
                (
                    "digital_verdict",
                    models.CharField(
                        choices=[
                            ("aprobado", "Aprobado para visita"),
                            ("observado", "Observado — requiere revisión"),
                            ("rechazado", "Rechazado"),
                        ],
                        max_length=20,
                        verbose_name="Veredicto digital",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("digital_completed", "Flujo digital completado"),
                            ("visit_scheduled", "Visita presencial programada"),
                            ("visit_completed", "Visita presencial completada"),
                            ("rejected", "Rechazado en flujo digital"),
                        ],
                        default="digital_completed",
                        max_length=30,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="User-Agent"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "scheduled_visit",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_visit_request",
                        to="verification.verificationvisit",
                        verbose_name="Visita presencial vinculada",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_visit_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario solicitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Visita VeriHome ID",
                "verbose_name_plural": "Solicitudes de Visita VeriHome ID",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="verificatio_user_id_1bbf05_idx",
                    ),
                    models.Index(
                        fields=["status"], name="verificatio_status_e46d4f_idx"
                    ),
                ],
            },
        ),
    ]
