# Generated by Django 4.2.7 on 2026-05-01 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import verification.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("verification", "0002_fieldvisitrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldVisitAct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "act_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Número de acta",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        help_text="Secciones I-VIII consolidadas: identificación, agente, consentimiento, biometría, cruces oficiales, validación documental, inmueble, score y observaciones.",
                        verbose_name="Contenido del acta",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=verification.models._field_visit_act_pdf_path,
                        verbose_name="PDF del acta",
                    ),
                ),
                (
                    "pdf_sha256",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="SHA-256 del PDF"
                    ),
                ),
                (
                    "verified_signature",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Firma del verificado"
                    ),
                ),
                (
                    "verified_signed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha firma verificado"
                    ),
                ),
                (
                    "agent_signature",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Firma del agente"
                    ),
                ),
                (
                    "agent_signed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha firma agente"
                    ),
                ),
                (
                    "lawyer_signed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha firma abogado"
                    ),
                ),
                (
                    "lawyer_tp_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="T.P. abogado"
                    ),
                ),
                (
                    "lawyer_full_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Nombre completo abogado",
                    ),
                ),
                (
                    "lawyer_cc",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Cédula abogado"
                    ),
                ),
                (
                    "lawyer_certificate_fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="Reservado para firma PAdES futura (C13).",
                        max_length=64,
                        verbose_name="Huella certificado .p12",
                    ),
                ),
                (
                    "prev_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Hash anterior"
                    ),
                ),
                (
                    "payload_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Hash de payload + PDF"
                    ),
                ),
                (
                    "final_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="Hash final del bloque",
                    ),
                ),
                (
                    "block_number",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Número de bloque",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador del agente"),
                            ("signed_by_parties", "Firmada por verificado y agente"),
                            ("signed_by_lawyer", "Firmada por abogado titulado"),
                            ("sealed", "Sellada en cadena"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "geolocation_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitud",
                    ),
                ),
                (
                    "geolocation_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitud",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "field_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="act",
                        to="verification.fieldvisitrequest",
                        verbose_name="Solicitud VeriHome ID",
                    ),
                ),
                (
                    "lawyer_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signed_acts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Abogado certificador",
                    ),
                ),
                (
                    "prev_act",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="next_act",
                        to="verification.fieldvisitact",
                        verbose_name="Acta anterior en cadena",
                    ),
                ),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="act",
                        to="verification.verificationvisit",
                        verbose_name="Visita presencial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acta VeriHome ID",
                "verbose_name_plural": "Actas VeriHome ID",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="verificatio_status_e6df1b_idx"
                    ),
                    models.Index(
                        fields=["block_number"], name="verificatio_block_n_1a0765_idx"
                    ),
                ],
            },
        ),
    ]
