# Generated by Django 4.2.7 on 2026-05-01 03:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verification", "0003_fieldvisitact"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldvisitact",
            name="final_verdict",
            field=models.CharField(
                choices=[
                    ("aprobado", "Aprobado"),
                    ("observado", "Observado"),
                    ("rechazado", "Rechazado"),
                ],
                default="rechazado",
                help_text="≥0.80 aprobado · ≥0.55 observado · <0.55 rechazado. Se recalcula automáticamente al save() con visit_score_total.",
                max_length=20,
                verbose_name="Veredicto final",
            ),
        ),
        migrations.AddField(
            model_name="fieldvisitact",
            name="total_score",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                help_text="Suma del score digital (0.0-0.5) + score visita (0.0-0.5). Se actualiza automáticamente al save().",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
                verbose_name="Score compuesto total",
            ),
        ),
        migrations.AddField(
            model_name="fieldvisitact",
            name="visit_score_breakdown",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Sub-puntajes 0.0-0.5 asignados por el agente: {cedula_real, observacion_visual, recibo_publico, comprobante_laboral, email_otp, telefono_otp, cruces_oficiales, inmueble_existe}",
                verbose_name="Score de visita desglosado",
            ),
        ),
        migrations.AddField(
            model_name="fieldvisitact",
            name="visit_score_total",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                help_text="Score parcial 0.0-0.5 que aporta la visita presencial",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(0.5),
                ],
                verbose_name="Score visita total",
            ),
        ),
    ]
