# Generated by Django 4.2.24 on 2026-05-18 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verification', '0004_fieldvisitact_final_verdict_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email donde se envió el código')),
                ('code_hash', models.CharField(max_length=64, verbose_name='Hash SHA-256 del código')),
                ('expires_at', models.DateTimeField(verbose_name='Vence')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='Consumido')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Intentos fallidos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP solicitante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'OTP Email',
                'verbose_name_plural': 'OTPs Email',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='verificatio_user_id_75865d_idx'), models.Index(fields=['expires_at'], name='verificatio_expires_4dd6f3_idx')],
            },
        ),
    ]
