# Generated by Django 4.2.24 on 2026-05-18 20:33

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid
import verification.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("verification", "0005_add_email_verification_otp"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=255,
                        upload_to=verification.models._public_receipt_upload_path,
                        verbose_name="Imagen del recibo",
                    ),
                ),
                (
                    "receipt_type",
                    models.CharField(
                        choices=[
                            ("electricity", "Energía"),
                            ("water", "Acueducto"),
                            ("gas", "Gas"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de recibo",
                    ),
                ),
                (
                    "ocr_text",
                    models.TextField(blank=True, verbose_name="Texto OCR (cliente)"),
                ),
                (
                    "declared_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Monto declarado",
                    ),
                ),
                (
                    "declared_address",
                    models.TextField(blank=True, verbose_name="Dirección declarada"),
                ),
                ("issue_date", models.DateField(verbose_name="Fecha emisión")),
                (
                    "address_match_score",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Similitud dirección",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("accepted", "Aceptado"), ("rejected", "Rechazado")],
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Motivo rechazo"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP solicitante"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_receipts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recibo público VeriHome ID",
                "verbose_name_plural": "Recibos públicos VeriHome ID",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="verificatio_user_id_51429c_idx",
                    ),
                    models.Index(
                        fields=["status"], name="verificatio_status_1bf932_idx"
                    ),
                ],
            },
        ),
    ]
