# Generated by Django 4.2.7 on 2025-07-06 17:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Crear'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('login', 'Iniciar Sesión'), ('logout', 'Cerrar Sesión'), ('view', 'Ver'), ('download', 'Descargar'), ('upload', 'Subir'), ('send', 'Enviar'), ('approve', 'Aprobar'), ('reject', 'Rechazar'), ('verify', 'Verificar')], max_length=20, verbose_name='Tipo de acción')),
                ('description', models.CharField(max_length=300, verbose_name='Descripción')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detalles adicionales')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Clave de sesión')),
                ('success', models.BooleanField(default=True, verbose_name='Exitosa')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actividad')),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('template_type', models.CharField(choices=[('welcome', 'Bienvenida'), ('verification', 'Verificación'), ('password_reset', 'Restablecimiento de Contraseña'), ('contract_notification', 'Notificación de Contrato'), ('payment_notification', 'Notificación de Pago'), ('message_notification', 'Notificación de Mensaje'), ('rating_invitation', 'Invitación de Calificación'), ('support_response', 'Respuesta de Soporte'), ('newsletter', 'Newsletter'), ('reminder', 'Recordatorio')], max_length=30, verbose_name='Tipo')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('html_content', models.TextField(verbose_name='Contenido HTML')),
                ('text_content', models.TextField(blank=True, verbose_name='Contenido de texto')),
                ('available_variables', models.JSONField(default=list, help_text='Lista de variables que se pueden usar en la plantilla', verbose_name='Variables disponibles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_default', models.BooleanField(default=False, verbose_name='Por defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Plantilla de Email',
                'verbose_name_plural': 'Plantillas de Email',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General'), ('landlords', 'Arrendadores'), ('tenants', 'Arrendatarios'), ('service_providers', 'Prestadores de Servicios'), ('payments', 'Pagos'), ('contracts', 'Contratos'), ('verification', 'Verificación'), ('technical', 'Técnico')], max_length=20, verbose_name='Categoría')),
                ('question', models.CharField(max_length=300, verbose_name='Pregunta')),
                ('answer', models.TextField(max_length=2000, verbose_name='Respuesta')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicada')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Número de visualizaciones')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Votos útiles')),
                ('not_helpful_count', models.PositiveIntegerField(default=0, verbose_name='Votos no útiles')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes',
                'ordering': ['category', 'order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('message', 'Nuevo Mensaje'), ('contract', 'Actualización de Contrato'), ('payment', 'Notificación de Pago'), ('property', 'Actualización de Propiedad'), ('rating', 'Nueva Calificación'), ('inquiry', 'Nueva Consulta'), ('system', 'Notificación del Sistema'), ('reminder', 'Recordatorio'), ('welcome', 'Bienvenida'), ('verification', 'Verificación')], max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(max_length=1000, verbose_name='Mensaje')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridad')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('is_email_sent', models.BooleanField(default=False, verbose_name='Email enviado')),
                ('is_push_sent', models.BooleanField(default=False, verbose_name='Push enviado')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('action_url', models.URLField(blank=True, verbose_name='URL de acción')),
                ('action_label', models.CharField(blank=True, max_length=50, verbose_name='Etiqueta de acción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='VeriHome', max_length=100, verbose_name='Nombre del sitio')),
                ('site_description', models.TextField(max_length=500, verbose_name='Descripción del sitio')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('support_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de soporte')),
                ('platform_commission_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Porcentaje de comisión de plataforma')),
                ('minimum_contract_duration', models.PositiveIntegerField(default=30, verbose_name='Duración mínima de contrato (días)')),
                ('maximum_contract_duration', models.PositiveIntegerField(default=3650, verbose_name='Duración máxima de contrato (días)')),
                ('require_identity_verification', models.BooleanField(default=True, verbose_name='Requerir verificación de identidad')),
                ('require_income_verification', models.BooleanField(default=True, verbose_name='Requerir verificación de ingresos')),
                ('auto_approve_verified_users', models.BooleanField(default=False, verbose_name='Aprobar automáticamente usuarios verificados')),
                ('max_messages_per_day', models.PositiveIntegerField(default=100, verbose_name='Máximo de mensajes por día')),
                ('message_retention_days', models.PositiveIntegerField(default=365, verbose_name='Días de retención de mensajes')),
                ('rating_scale_max', models.PositiveIntegerField(default=10, verbose_name='Escala máxima de calificación')),
                ('minimum_ratings_for_badge', models.PositiveIntegerField(default=5, verbose_name='Mínimo de calificaciones para badge')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Título meta')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Descripción meta')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Palabras clave meta')),
                ('google_analytics_id', models.CharField(blank=True, max_length=20, verbose_name='ID de Google Analytics')),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=20, verbose_name='ID de Facebook Pixel')),
                ('is_maintenance_mode', models.BooleanField(default=False, verbose_name='Modo de mantenimiento')),
                ('maintenance_message', models.TextField(blank=True, verbose_name='Mensaje de mantenimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuraciones del Sitio',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=20, unique=True, verbose_name='Número de ticket')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('description', models.TextField(max_length=2000, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('technical', 'Técnico'), ('billing', 'Facturación'), ('account', 'Cuenta'), ('property', 'Propiedad'), ('contract', 'Contrato'), ('verification', 'Verificación'), ('other', 'Otro')], max_length=20, verbose_name='Categoría')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En Progreso'), ('waiting_customer', 'Esperando Cliente'), ('resolved', 'Resuelto'), ('closed', 'Cerrado')], default='open', max_length=20, verbose_name='Estado')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
            ],
            options={
                'verbose_name': 'Ticket de Soporte',
                'verbose_name_plural': 'Tickets de Soporte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(max_length=1000, verbose_name='Descripción')),
                ('level', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('critical', 'Crítico')], max_length=10, verbose_name='Nivel')),
                ('category', models.CharField(choices=[('security', 'Seguridad'), ('performance', 'Rendimiento'), ('business', 'Negocio'), ('technical', 'Técnico'), ('compliance', 'Cumplimiento')], max_length=20, verbose_name='Categoría')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='Reconocida')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resuelta')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas de resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de reconocimiento')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
            ],
            options={
                'verbose_name': 'Alerta del Sistema',
                'verbose_name_plural': 'Alertas del Sistema',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('user_registration', 'Registro de Usuarios'), ('property_listing', 'Publicación de Propiedades'), ('contract_creation', 'Creación de Contratos'), ('message_sent', 'Mensajes Enviados'), ('payment_processed', 'Pagos Procesados'), ('rating_submitted', 'Calificaciones Enviadas'), ('page_view', 'Visualizaciones de Página'), ('search_query', 'Consultas de Búsqueda')], max_length=30, verbose_name='Tipo de métrica')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Conteo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Métrica del Sistema',
                'verbose_name_plural': 'Métricas del Sistema',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TicketResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=2000, verbose_name='Mensaje')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Nota interna')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_attachments/', verbose_name='Archivo adjunto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Respuesta de Ticket',
                'verbose_name_plural': 'Respuestas de Tickets',
                'ordering': ['created_at'],
            },
        ),
    ]
