# Generated by Django 4.2.7 on 2026-03-20 23:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre completo"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("subject", models.CharField(max_length=300, verbose_name="Asunto")),
                ("message", models.TextField(verbose_name="Mensaje")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nuevo"),
                            ("read", "Leído"),
                            ("replied", "Respondido"),
                            ("archived", "Archivado"),
                        ],
                        default="new",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Notas internas"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "email_notified",
                    models.BooleanField(
                        default=False, verbose_name="Notificación enviada"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de recepción"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de Contacto",
                "verbose_name_plural": "Mensajes de Contacto",
                "ordering": ["-created_at"],
            },
        ),
    ]
