# Generated by Django 4.2.7 on 2026-03-23 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="contact_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="core.contactmessage",
                verbose_name="Mensaje de contacto origen",
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="department",
            field=models.CharField(
                choices=[
                    ("general", "Consultas Generales"),
                    ("verification_agents", "Agentes de Verificación"),
                    ("legal", "Área Jurídica"),
                    ("ceo", "Dirección / CEO"),
                    ("marketing", "Marketing"),
                    ("technical", "Soporte Técnico"),
                    ("billing", "Facturación y Pagos"),
                ],
                default="general",
                max_length=25,
                verbose_name="Departamento destino",
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="category",
            field=models.CharField(
                choices=[
                    ("technical", "Técnico"),
                    ("billing", "Facturación"),
                    ("account", "Cuenta"),
                    ("property", "Propiedad"),
                    ("contract", "Contrato"),
                    ("verification", "Verificación"),
                    ("legal", "Jurídico"),
                    ("services", "Servicios"),
                    ("other", "Otro"),
                ],
                max_length=20,
                verbose_name="Categoría",
            ),
        ),
    ]
