# Generated by Django 4.2.7 on 2026-03-24 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_supportticket_contact_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportticket",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Null para tickets creados desde formulario de contacto público",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
