# Generated by Django 4.2.7 on 2025-07-06 17:50

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Número de contrato')),
                ('contract_type', models.CharField(choices=[('rental_urban', 'Arrendamiento de Vivienda Urbana'), ('rental_commercial', 'Arrendamiento de Local Comercial'), ('rental_room', 'Arrendamiento de Habitación'), ('rental_rural', 'Arrendamiento de Lote de Terreno Rural'), ('service_provider', 'Contrato de Prestación de Servicios'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de contrato')),
                ('title', models.CharField(max_length=200, verbose_name='Título del contrato')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Descripción')),
                ('content', models.TextField(verbose_name='Contenido del contrato')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de finalización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending_review', 'Pendiente de Revisión'), ('pending_signature', 'Pendiente de Firma'), ('partially_signed', 'Parcialmente Firmado'), ('fully_signed', 'Completamente Firmado'), ('active', 'Activo'), ('expired', 'Vencido'), ('terminated', 'Terminado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado')),
                ('is_renewable', models.BooleanField(default=False, verbose_name='Renovable automáticamente')),
                ('auto_renewal_notice_days', models.PositiveIntegerField(default=30, verbose_name='Días de aviso para renovación automática')),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Renta mensual')),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Depósito de garantía')),
                ('late_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Recargo por mora')),
                ('variables_data', models.JSONField(default=dict, help_text='Datos específicos utilizados en el contrato', verbose_name='Datos de variables')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='contracts/pdfs/', verbose_name='Archivo PDF del contrato')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de generación PDF')),
                ('is_downloadable', models.BooleanField(default=False, verbose_name='Descargable')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amendment_number', models.CharField(max_length=20, verbose_name='Número de enmienda')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la enmienda')),
                ('description', models.TextField(max_length=1000, verbose_name='Descripción de cambios')),
                ('content', models.TextField(verbose_name='Contenido de la enmienda')),
                ('changes_summary', models.JSONField(default=dict, help_text='Estructura de los cambios realizados', verbose_name='Resumen de cambios')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending_approval', 'Pendiente de Aprobación'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('active', 'Activa')], default='draft', max_length=20, verbose_name='Estado')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vigencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
            ],
            options={
                'verbose_name': 'Enmienda de Contrato',
                'verbose_name_plural': 'Enmiendas de Contratos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('document_type', models.CharField(choices=[('addendum', 'Addendum'), ('attachment', 'Anexo'), ('evidence', 'Evidencia'), ('correspondence', 'Correspondencia'), ('invoice', 'Factura'), ('receipt', 'Recibo'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de documento')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Descripción')),
                ('file', models.FileField(upload_to='contracts/documents/', verbose_name='Archivo')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño del archivo (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Fecha del documento')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
            ],
            options={
                'verbose_name': 'Documento de Contrato',
                'verbose_name_plural': 'Documentos de Contratos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_start_date', models.DateField(verbose_name='Nueva fecha de inicio')),
                ('new_end_date', models.DateField(verbose_name='Nueva fecha de finalización')),
                ('new_monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Nueva renta mensual')),
                ('rent_increase_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Porcentaje de aumento de renta')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('executed', 'Ejecutada')], default='pending', max_length=20, verbose_name='Estado')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('terms_changes', models.JSONField(default=dict, help_text='Cambios específicos en los términos del contrato', verbose_name='Cambios en términos')),
                ('notes', models.TextField(blank=True, max_length=1000, verbose_name='Notas adicionales')),
                ('response_deadline', models.DateField(verbose_name='Fecha límite de respuesta')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de ejecución')),
            ],
            options={
                'verbose_name': 'Renovación de Contrato',
                'verbose_name_plural': 'Renovaciones de Contratos',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_type', models.CharField(choices=[('digital', 'Firma Digital'), ('electronic', 'Firma Electrónica'), ('biometric', 'Firma Biométrica'), ('webcam', 'Firma con Cámara Web')], max_length=20, verbose_name='Tipo de firma')),
                ('authentication_method', models.CharField(choices=[('password', 'Contraseña'), ('webcam_face', 'Reconocimiento Facial'), ('webcam_document', 'Documento de Identidad'), ('biometric_fingerprint', 'Huella Digital'), ('sms_verification', 'Verificación SMS'), ('email_verification', 'Verificación Email')], max_length=30, verbose_name='Método de autenticación')),
                ('signature_data', models.TextField(help_text='Firma codificada o hash', verbose_name='Datos de la firma')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Imagen de la firma')),
                ('face_verification_data', models.JSONField(blank=True, default=dict, help_text='Datos de reconocimiento facial', verbose_name='Datos de verificación facial')),
                ('document_verification_data', models.JSONField(blank=True, default=dict, help_text='Datos de verificación de documento de identidad', verbose_name='Datos de verificación de documento')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('geolocation', models.JSONField(blank=True, default=dict, verbose_name='Geolocalización')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de firma')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Firma válida')),
                ('verification_hash', models.CharField(max_length=256, verbose_name='Hash de verificación')),
                ('notes', models.TextField(blank=True, max_length=500, verbose_name='Notas')),
                ('security_checks', models.JSONField(default=dict, help_text='Resultados de verificaciones de seguridad', verbose_name='Verificaciones de seguridad')),
                ('biometric_data', models.JSONField(blank=True, default=dict, help_text='Datos completos de verificación biométrica', verbose_name='Datos biométricos completos')),
                ('device_fingerprint', models.JSONField(blank=True, default=dict, help_text='Información única del dispositivo utilizado', verbose_name='Huella digital del dispositivo')),
                ('verification_level', models.CharField(choices=[('basic', 'Básica'), ('enhanced', 'Mejorada'), ('maximum', 'Máxima')], default='basic', max_length=20, verbose_name='Nivel de verificación')),
                ('certificate_chain', models.JSONField(blank=True, default=dict, help_text='Cadena de certificados digitales', verbose_name='Cadena de certificados')),
                ('timestamp_token', models.TextField(blank=True, help_text='Token de sellado de tiempo RFC 3161', verbose_name='Token de marca temporal')),
                ('blockchain_hash', models.CharField(blank=True, help_text='Hash de la transacción en blockchain para inmutabilidad', max_length=64, verbose_name='Hash en blockchain')),
            ],
            options={
                'verbose_name': 'Firma de Contrato',
                'verbose_name_plural': 'Firmas de Contratos',
                'ordering': ['signed_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la plantilla')),
                ('template_type', models.CharField(choices=[('rental_urban', 'Arrendamiento de Vivienda Urbana'), ('rental_commercial', 'Arrendamiento de Local Comercial'), ('rental_room', 'Arrendamiento de Habitación'), ('rental_rural', 'Arrendamiento de Lote de Terreno Rural'), ('service_provider', 'Contrato de Prestación de Servicios'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de plantilla')),
                ('content', models.TextField(verbose_name='Contenido del contrato')),
                ('variables', models.JSONField(default=list, help_text='Lista de variables que se pueden usar en la plantilla', verbose_name='Variables disponibles')),
                ('is_default', models.BooleanField(default=False, verbose_name='Plantilla por defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Plantilla de Contrato',
                'verbose_name_plural': 'Plantillas de Contratos',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContractTermination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('mutual_agreement', 'Acuerdo Mutuo'), ('breach_of_contract', 'Incumplimiento de Contrato'), ('non_payment', 'Falta de Pago'), ('property_damage', 'Daño a la Propiedad'), ('violation_of_terms', 'Violación de Términos'), ('early_termination', 'Terminación Anticipada'), ('natural_expiration', 'Vencimiento Natural'), ('force_majeure', 'Fuerza Mayor'), ('other', 'Otro')], max_length=30, verbose_name='Razón de terminación')),
                ('description', models.TextField(max_length=1000, verbose_name='Descripción detallada')),
                ('termination_date', models.DateField(verbose_name='Fecha de terminación')),
                ('notice_date', models.DateField(verbose_name='Fecha de aviso')),
                ('effective_date', models.DateField(verbose_name='Fecha efectiva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('penalty_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto de penalización')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto de reembolso')),
                ('final_payment_due', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Pago final adeudado')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprobada')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('termination_document', models.FileField(blank=True, null=True, upload_to='contracts/terminations/', verbose_name='Documento de terminación')),
            ],
            options={
                'verbose_name': 'Terminación de Contrato',
                'verbose_name_plural': 'Terminaciones de Contratos',
                'ordering': ['-created_at'],
            },
        ),
    ]
