# Generated by Django 5.2.3 on 2025-06-28 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='primary_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_primary', to=settings.AUTH_USER_MODEL, verbose_name='Parte principal (Arrendador/Cliente)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='properties.property'),
        ),
        migrations.AddField(
            model_name='contract',
            name='secondary_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_secondary', to=settings.AUTH_USER_MODEL, verbose_name='Parte secundaria (Arrendatario/Prestador)'),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_amendments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_amendments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='contracts.contractdocument'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_contract_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractrenewal',
            name='new_contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renewal_from', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractrenewal',
            name='original_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractrenewal',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_renewals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='witnessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='witnessed_signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='contracts.contracttemplate'),
        ),
        migrations.AddField(
            model_name='contracttermination',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_terminations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contracttermination',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='termination', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contracttermination',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_terminations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='contractsignature',
            unique_together={('contract', 'signer')},
        ),
    ]
