# Generated by Django 4.2.7 on 2025-07-21 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching', '0003_matchrequest_contract_generated_at_and_more'),
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColombianContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_type', models.CharField(choices=[('ARR_VIV_URB', 'Contrato de Arrendamiento de Vivienda Urbana (Ley 820 de 2003)'), ('ARR_COM', 'Contrato de Arrendamiento de Local Comercial'), ('PREST_SERV', 'Contrato de Prestación de Servicios (Art. 1495 CC)'), ('COMPRA_VENTA', 'Contrato de Compraventa de Bien Inmueble'), ('ADMIN_INM', 'Contrato de Administración de Inmueble'), ('CORRETAJE', 'Contrato de Corretaje Inmobiliario'), ('PROMESA', 'Promesa de Compraventa (Art. 89 Ley 153/1887)')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING_VER', 'Pendiente Verificación de Identidad'), ('PENDING_SIG', 'Pendiente de Firmas'), ('PARTIAL_SIG', 'Parcialmente Firmado'), ('SIGNED', 'Firmado por Todas las Partes'), ('NOTARIZED', 'Autenticado en Notaría'), ('REGISTERED', 'Registrado (Oficina de Registro)'), ('ACTIVE', 'Vigente'), ('TERMINATED', 'Terminado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20)),
                ('landlord_verified', models.BooleanField(default=False)),
                ('tenant_verified', models.BooleanField(default=False)),
                ('landlord_id_type', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('NIT', 'NIT (Persona Jurídica)')], max_length=20)),
                ('landlord_id_number', models.CharField(max_length=20)),
                ('tenant_id_type', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], max_length=20)),
                ('tenant_id_number', models.CharField(max_length=20)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rent_increment_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='% incremento anual según IPC', max_digits=5, null=True)),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('administration_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_due_day', models.IntegerField(default=5, help_text='Día del mes para pago de canon')),
                ('guarantee_type', models.CharField(blank=True, choices=[('CODEUDOR', 'Codeudor Solidario'), ('FIANZA', 'Fianza o Aval Bancario'), ('SEGURO', 'Seguro de Arrendamiento'), ('DEPOSITO', 'Depósito en Garantía')], max_length=30, null=True)),
                ('utilities_included', models.JSONField(default=dict, help_text="{'agua': True, 'luz': False, 'gas': False, 'internet': False}")),
                ('property_inventory', models.JSONField(default=list, help_text='Lista detallada de elementos del inmueble')),
                ('custom_clauses', models.JSONField(default=list)),
                ('penalties_clauses', models.JSONField(default=dict)),
                ('landlord_signature', models.JSONField(blank=True, null=True)),
                ('tenant_signature', models.JSONField(blank=True, null=True)),
                ('witness_1_signature', models.JSONField(blank=True, null=True)),
                ('witness_2_signature', models.JSONField(blank=True, null=True)),
                ('notary_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notary_city', models.CharField(blank=True, max_length=100, null=True)),
                ('notarization_date', models.DateTimeField(blank=True, null=True)),
                ('notary_protocol_number', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_office', models.CharField(blank=True, max_length=200, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documents', models.JSONField(default=dict, help_text='URLs de documentos: certificados, paz y salvos, etc.')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_created', to=settings.AUTH_USER_MODEL)),
                ('match_request', models.OneToOneField(help_text='Solo se pueden crear contratos desde matches aceptados', on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='matching.matchrequest')),
            ],
            options={
                'verbose_name': 'Contrato Legal Colombiano',
                'verbose_name_plural': 'Contratos Legales Colombianos',
                'db_table': 'colombian_contracts',
            },
        ),
        migrations.CreateModel(
            name='LegalClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_type', models.CharField(choices=[('ARR_VIV_URB', 'Contrato de Arrendamiento de Vivienda Urbana (Ley 820 de 2003)'), ('ARR_COM', 'Contrato de Arrendamiento de Local Comercial'), ('PREST_SERV', 'Contrato de Prestación de Servicios (Art. 1495 CC)'), ('COMPRA_VENTA', 'Contrato de Compraventa de Bien Inmueble'), ('ADMIN_INM', 'Contrato de Administración de Inmueble'), ('CORRETAJE', 'Contrato de Corretaje Inmobiliario'), ('PROMESA', 'Promesa de Compraventa (Art. 89 Ley 153/1887)')], max_length=20)),
                ('clause_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('legal_reference', models.CharField(help_text='Referencia legal (ej: Art. 1973 CC, Ley 820/2003)', max_length=200)),
                ('requires_customization', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['contract_type', 'clause_number'],
                'unique_together': {('contract_type', 'clause_number')},
            },
        ),
        migrations.CreateModel(
            name='ContractMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milestone_type', models.CharField(choices=[('PAGO_MENSUAL', 'Pago Mensual de Arriendo'), ('ENTREGA_INMUEBLE', 'Entrega del Inmueble'), ('DEVOLUCION_INMUEBLE', 'Devolución del Inmueble'), ('PAGO_SERVICIOS', 'Pago de Servicios'), ('MANTENIMIENTO', 'Mantenimiento Programado'), ('INSPECCION', 'Inspección Periódica')], max_length=30)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Proceso'), ('COMPLETED', 'Completado'), ('OVERDUE', 'Vencido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.JSONField(default=list, help_text='Evidencias de cumplimiento')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='contracts.colombiancontract')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractGuarantee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guarantee_type', models.CharField(choices=[('CODEUDOR', 'Codeudor Solidario'), ('FIANZA_BANCARIA', 'Fianza Bancaria'), ('SEGURO_ARRENDAMIENTO', 'Seguro de Arrendamiento'), ('DEPOSITO_GARANTIA', 'Depósito en Garantía'), ('PAGARE', 'Pagaré en Blanco con Carta de Instrucciones')], max_length=30)),
                ('guarantor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guarantor_id_type', models.CharField(blank=True, max_length=20, null=True)),
                ('guarantor_id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('guarantor_verified', models.BooleanField(default=False)),
                ('guarantor_income_verified', models.BooleanField(default=False)),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_company', models.CharField(blank=True, max_length=200, null=True)),
                ('coverage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('documents', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('ACTIVE', 'Activo'), ('EXPIRED', 'Vencido')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to='contracts.colombiancontract')),
            ],
        ),
        migrations.AddIndex(
            model_name='colombiancontract',
            index=models.Index(fields=['status', 'contract_type'], name='colombian_c_status_2de66c_idx'),
        ),
        migrations.AddIndex(
            model_name='colombiancontract',
            index=models.Index(fields=['landlord_id_number', 'tenant_id_number'], name='colombian_c_landlor_c5f256_idx'),
        ),
    ]
