# Generated by Django 4.2.7 on 2025-06-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsignature',
            name='biometric_data',
            field=models.JSONField(blank=True, default=dict, help_text='Datos completos de verificación biométrica', verbose_name='Datos biométricos completos'),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='blockchain_hash',
            field=models.CharField(blank=True, help_text='Hash de la transacción en blockchain para inmutabilidad', max_length=64, verbose_name='Hash en blockchain'),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='certificate_chain',
            field=models.JSONField(blank=True, default=dict, help_text='Cadena de certificados digitales', verbose_name='Cadena de certificados'),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='device_fingerprint',
            field=models.JSONField(blank=True, default=dict, help_text='Información única del dispositivo utilizado', verbose_name='Huella digital del dispositivo'),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='timestamp_token',
            field=models.TextField(blank=True, help_text='Token de sellado de tiempo RFC 3161', verbose_name='Token de marca temporal'),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='verification_level',
            field=models.CharField(choices=[('basic', 'Básica'), ('enhanced', 'Mejorada'), ('maximum', 'Máxima')], default='basic', max_length=20, verbose_name='Nivel de verificación'),
        ),
    ]
