# Generated by Django 4.2.7 on 2025-08-04 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0003_colombiancontract_legalclause_contractmilestone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending_review', 'Pendiente de Revisión'), ('pdf_generated', 'PDF Generado - Pendiente Edición'), ('ready_for_authentication', 'Listo para Autenticación'), ('pending_authentication', 'Pendiente de Autenticación Biométrica'), ('authenticated_pending_signature', 'Autenticado - Pendiente de Firma'), ('pending_signature', 'Pendiente de Firma'), ('partially_signed', 'Parcialmente Firmado'), ('fully_signed', 'Completamente Firmado'), ('active', 'Activo'), ('expired', 'Vencido'), ('terminated', 'Terminado'), ('cancelled', 'Cancelado')], default='draft', max_length=35, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='BiometricAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('failed', 'Fallido'), ('expired', 'Expirado')], default='pending', max_length=20, verbose_name='Estado')),
                ('face_front_image', models.ImageField(blank=True, null=True, upload_to='biometric/faces/', verbose_name='Foto frontal del rostro')),
                ('face_side_image', models.ImageField(blank=True, null=True, upload_to='biometric/faces/', verbose_name='Foto lateral del rostro')),
                ('document_image', models.ImageField(blank=True, null=True, upload_to='biometric/documents/', verbose_name='Foto del documento de identidad')),
                ('document_with_face_image', models.ImageField(blank=True, null=True, upload_to='biometric/verification/', verbose_name='Foto del documento junto al rostro')),
                ('voice_recording', models.FileField(blank=True, null=True, upload_to='biometric/voice/', verbose_name='Grabación de voz')),
                ('voice_text', models.TextField(blank=True, help_text='Texto que el usuario debe leer', verbose_name='Texto de verificación de voz')),
                ('document_type', models.CharField(choices=[('cedula_ciudadania', 'Cédula de Ciudadanía'), ('cedula_extranjeria', 'Cédula de Extranjería'), ('pasaporte', 'Pasaporte'), ('licencia_conducir', 'Licencia de Conducir'), ('tarjeta_identidad', 'Tarjeta de Identidad')], max_length=30, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(blank=True, max_length=50, verbose_name='Número de documento')),
                ('document_expiry_date', models.DateField(blank=True, null=True, verbose_name='Fecha de expiración del documento')),
                ('facial_analysis', models.JSONField(default=dict, help_text='Resultados del análisis de reconocimiento facial', verbose_name='Análisis facial')),
                ('document_analysis', models.JSONField(default=dict, help_text='Resultados de la validación del documento', verbose_name='Análisis del documento')),
                ('voice_analysis', models.JSONField(default=dict, help_text='Análisis de la grabación de voz', verbose_name='Análisis de voz')),
                ('face_confidence_score', models.FloatField(default=0.0, verbose_name='Puntuación de confianza facial')),
                ('document_confidence_score', models.FloatField(default=0.0, verbose_name='Puntuación de confianza del documento')),
                ('voice_confidence_score', models.FloatField(default=0.0, verbose_name='Puntuación de confianza de voz')),
                ('overall_confidence_score', models.FloatField(default=0.0, verbose_name='Puntuación general de confianza')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('device_info', models.JSONField(default=dict, verbose_name='Información del dispositivo')),
                ('geolocation', models.JSONField(default=dict, verbose_name='Geolocalización')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado el')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado el')),
                ('expires_at', models.DateTimeField(verbose_name='Expira el')),
                ('security_checks', models.JSONField(default=dict, help_text='Resultados de verificaciones adicionales de seguridad', verbose_name='Verificaciones de seguridad')),
                ('integrity_hash', models.CharField(blank=True, max_length=256, verbose_name='Hash de integridad')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_authentications', to='contracts.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_authentications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autenticación Biométrica',
                'verbose_name_plural': 'Autenticaciones Biométricas',
                'ordering': ['-started_at'],
                'unique_together': {('contract', 'user')},
            },
        ),
    ]
