# Generated by Django 4.2.7 on 2025-08-05 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0005_contractobjection_landlordcontrolledcontract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractworkflowhistory',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Crear Contrato'), ('UPDATE', 'Actualizar Contrato'), ('STATE_CHANGE', 'Cambio de Estado'), ('INVITATION_SENT', 'Invitación Enviada'), ('INVITATION_RESENT', 'Invitación Reenviada'), ('INVITATION_ACCEPTED', 'Invitación Aceptada'), ('INVITE_TENANT', 'Invitar Arrendatario'), ('ACCEPT_INVITATION', 'Aceptar Invitación'), ('SUBMIT_OBJECTION', 'Presentar Objeción'), ('RESPOND_OBJECTION', 'Responder Objeción'), ('APPROVE', 'Aprobar Contrato'), ('SIGN', 'Firmar Contrato'), ('PUBLISH', 'Publicar Contrato'), ('CANCEL', 'Cancelar Contrato'), ('TERMINATE', 'Terminar Contrato'), ('ADD_GUARANTEE', 'Agregar Garantía'), ('MODIFY_GUARANTEE', 'Modificar Garantía'), ('VERIFY_GUARANTEE', 'Verificar Garantía'), ('SYSTEM_ACTION', 'Acción del Sistema')], max_length=20, verbose_name='Tipo de acción'),
        ),
        migrations.CreateModel(
            name='ContractInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('tenant_email', models.EmailField(max_length=254)),
                ('tenant_phone', models.CharField(blank=True, max_length=20)),
                ('tenant_name', models.CharField(default='Arrendatario', max_length=200)),
                ('invitation_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=10)),
                ('personal_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('opened', 'Abierto'), ('accepted', 'Aceptado'), ('expired', 'Expirado'), ('failed', 'Fallido')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_resent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='contracts.landlordcontrolledcontract')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token_hash'], name='contracts_c_token_h_a3172e_idx'), models.Index(fields=['status', 'expires_at'], name='contracts_c_status_2f494c_idx'), models.Index(fields=['contract', 'status'], name='contracts_c_contrac_06c712_idx')],
            },
        ),
    ]
