# Generated by Django 4.2.7 on 2025-08-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_contractworkflowhistory_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending_review', 'Pendiente de Revisión'), ('pdf_generated', 'PDF Generado - Pendiente Edición'), ('ready_for_authentication', 'Listo para Autenticación'), ('pending_authentication', 'Pendiente de Autenticación Biométrica'), ('authenticated_pending_signature', 'Autenticado - Pendiente de Firma'), ('pending_signature', 'Pendiente de Firma'), ('partially_signed', 'Parcialmente Firmado'), ('fully_signed', 'Completamente Firmado'), ('active', 'Activo'), ('en_ejecucion', 'En Ejecución'), ('expired', 'Vencido'), ('terminated', 'Terminado'), ('cancelled', 'Cancelado')], default='draft', max_length=35, verbose_name='Estado'),
        ),
    ]
