# Generated by Django 4.2.7 on 2025-08-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_alter_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='execution_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio de Ejecución'),
        ),
        migrations.AddField(
            model_name='contract',
            name='keys_delivered',
            field=models.BooleanField(default=False, verbose_name='Llaves Entregadas'),
        ),
        migrations.AddField(
            model_name='contract',
            name='keys_delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega de Llaves'),
        ),
        migrations.AddField(
            model_name='contract',
            name='keys_delivery_notes',
            field=models.TextField(blank=True, verbose_name='Notas de Entrega'),
        ),
        migrations.AddField(
            model_name='contract',
            name='landlord_auth_completed',
            field=models.BooleanField(default=False, verbose_name='Autenticación del Arrendador Completada'),
        ),
        migrations.AddField(
            model_name='contract',
            name='landlord_auth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Autenticación del Arrendador'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant_auth_completed',
            field=models.BooleanField(default=False, verbose_name='Autenticación del Arrendatario Completada'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant_auth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Autenticación del Arrendatario'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant_review_comments',
            field=models.TextField(blank=True, help_text='Comentarios o cambios solicitados por el arrendatario', verbose_name='Comentarios del Arrendatario'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant_review_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('reviewing', 'En Revisión'), ('approved', 'Aprobado'), ('changes_requested', 'Cambios Solicitados')], default='pending', max_length=30, verbose_name='Estado de Revisión del Arrendatario'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión del Arrendatario'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending_tenant_review', 'Pendiente Revisión del Arrendatario'), ('tenant_changes_requested', 'Cambios Solicitados por Arrendatario'), ('pending_review', 'Pendiente de Revisión'), ('pdf_generated', 'PDF Generado - Pendiente Edición'), ('ready_for_authentication', 'Listo para Autenticación'), ('pending_landlord_authentication', 'Pendiente Autenticación del Arrendador'), ('pending_tenant_authentication', 'Pendiente Autenticación del Arrendatario'), ('pending_authentication', 'Pendiente de Autenticación Biométrica'), ('authenticated_pending_signature', 'Autenticado - Pendiente de Firma'), ('pending_signature', 'Pendiente de Firma'), ('partially_signed', 'Parcialmente Firmado'), ('fully_signed', 'Completamente Firmado'), ('pending_move_in', 'Pendiente Entrega de Llaves'), ('active', 'Activo'), ('en_ejecucion', 'En Ejecución'), ('expired', 'Vencido'), ('terminated', 'Terminado'), ('cancelled', 'Cancelado')], default='draft', max_length=35, verbose_name='Estado'),
        ),
    ]
