# Generated by Django 4.2.7 on 2025-08-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_update_document_types'),
        ('contracts', '0009_contract_execution_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='tenant_documents',
            field=models.ManyToManyField(blank=True, help_text='Documentos subidos durante el proceso de solicitud', related_name='associated_contracts', to='requests.tenantdocument', verbose_name='Documentos del Inquilino'),
        ),
    ]
