# Generated by Django 4.2.7 on 2025-08-23 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0010_contract_tenant_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAdditionalClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Cláusula')),
                ('content', models.TextField(verbose_name='Contenido de la Cláusula')),
                ('clause_number', models.PositiveIntegerField(verbose_name='Número de Cláusula')),
                ('ordinal_text', models.CharField(help_text='Ej: UNDÉCIMA, DUODÉCIMA, etc.', max_length=50, verbose_name='Texto Ordinal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el contrato', verbose_name='Orden')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_clauses', to='contracts.contract')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contract_clauses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cláusula Adicional de Contrato',
                'verbose_name_plural': 'Cláusulas Adicionales de Contratos',
                'ordering': ['contract', 'order', 'clause_number'],
                'unique_together': {('contract', 'clause_number')},
            },
        ),
    ]
