# Generated by Django 4.2.7 on 2025-09-17 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0011_contractadditionalclause'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='guarantor',
            field=models.ForeignKey(blank=True, help_text='Usuario que actúa como garante o codeudor del contrato', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_as_guarantor', to=settings.AUTH_USER_MODEL, verbose_name='Garante/Codeudor'),
        ),
    ]
