# Generated by Django 4.2.7 on 2025-10-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0012_contract_guarantor"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="has_objections",
            field=models.BooleanField(default=False, verbose_name="Tiene Objeciones"),
        ),
        migrations.AddField(
            model_name="contract",
            name="objections_resolved",
            field=models.BooleanField(
                default=False, verbose_name="Objeciones Resueltas"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="tenant_approved",
            field=models.BooleanField(
                default=False, verbose_name="Arrendatario Aprobó"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="tenant_approved_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Fecha de Aprobación del Arrendatario",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador del Arrendador"),
                    ("tenant_review", "En Revisión por Arrendatario"),
                    ("tenant_approved", "Aprobado por Arrendatario"),
                    ("objections_pending", "Objeciones Pendientes"),
                    ("tenant_biometric", "Autenticación del Arrendatario"),
                    ("guarantor_biometric", "Autenticación del Codeudor"),
                    ("landlord_biometric", "Autenticación del Arrendador"),
                    ("biometric_completed", "Autenticación Biométrica Completa"),
                    ("ready_to_publish", "Listo para Publicar"),
                    ("published", "Publicado - Vida Jurídica"),
                    ("active", "Contrato Activo"),
                    ("expired", "Vencido"),
                    ("terminated", "Terminado"),
                    ("cancelled", "Cancelado"),
                ],
                default="draft",
                max_length=50,
                verbose_name="Estado",
            ),
        ),
    ]
