# Generated by Django 4.2.7 on 2025-10-05 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0005_matchrequest_workflow_stage_and_more"),
        ("contracts", "0013_clean_workflow_states"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="match_request",
            field=models.OneToOneField(
                blank=True,
                help_text="Match request del que se generó este contrato automáticamente",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unified_contract",
                to="matching.matchrequest",
                verbose_name="Solicitud de Match Original",
            ),
        ),
    ]
