# Generated by Django 4.2.7 on 2025-12-03 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contracts", "0014_add_match_request_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landlordcontrolledcontract",
            name="current_state",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Borrador del Arrendador"),
                    ("LANDLORD_COMPLETING", "Arrendador Completando Datos"),
                    ("TENANT_INVITED", "Arrendatario Invitado"),
                    ("TENANT_REVIEWING", "En Revisión por Arrendatario"),
                    (
                        "MODIFICATION_REQUESTED",
                        "Modificación Solicitada por Arrendatario",
                    ),
                    ("UNDER_MODIFICATION", "Arrendador Modificando Borrador"),
                    ("OBJECTIONS_PENDING", "Objeciones Pendientes de Respuesta"),
                    ("NEGOTIATION_IN_PROGRESS", "Negociación en Progreso"),
                    ("APPROVED_BY_TENANT", "Aprobado por Arrendatario"),
                    ("REJECTED_BY_TENANT", "Rechazado por Arrendatario"),
                    ("REJECTED_BY_LANDLORD", "Solicitud de Modificación Rechazada"),
                    ("TENANT_DATA_PENDING", "Esperando Datos del Arrendatario"),
                    (
                        "TENANT_AUTHENTICATION",
                        "Arrendatario en Proceso de Autenticación",
                    ),
                    ("TENANT_SIGNED", "Firmado por Arrendatario"),
                    (
                        "LANDLORD_AUTHENTICATION",
                        "Arrendador en Proceso de Autenticación",
                    ),
                    ("LANDLORD_SIGNED", "Firmado por Arrendador"),
                    ("READY_TO_PUBLISH", "Listo para Publicar"),
                    ("PUBLISHED", "Publicado - Vida Jurídica"),
                    ("ACTIVE", "Contrato Activo"),
                    ("EXPIRED", "Vencido"),
                    ("TERMINATED", "Terminado"),
                    ("CANCELLED", "Cancelado"),
                ],
                default="DRAFT",
                max_length=30,
                verbose_name="Estado actual",
            ),
        ),
        migrations.CreateModel(
            name="ContractModificationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "requested_changes",
                    models.JSONField(
                        default=dict,
                        help_text='Estructura: { "field_name": { "current_value": "...", "requested_value": "...", "reason": "..." } }',
                        verbose_name="Cambios Solicitados",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Razón general por la cual se solicitan modificaciones",
                        verbose_name="Justificación General",
                    ),
                ),
                (
                    "revision_number",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Contador de ciclos de revisión (máximo 2)",
                        verbose_name="Número de Revisión",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente de Revisión"),
                            ("ACCEPTED", "Aceptada por Arrendador"),
                            ("REJECTED", "Rechazada por Arrendador"),
                            ("IMPLEMENTED", "Modificación Implementada"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "landlord_response",
                    models.TextField(
                        blank=True,
                        help_text="Comentarios del arrendador al aceptar o rechazar",
                        null=True,
                        verbose_name="Respuesta del Arrendador",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Solicitud"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha en que el arrendador respondió",
                        null=True,
                        verbose_name="Fecha de Respuesta",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modification_requests",
                        to="contracts.landlordcontrolledcontract",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modification_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Modificación",
                "verbose_name_plural": "Solicitudes de Modificación",
                "db_table": "contract_modification_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["contract", "status"],
                        name="contract_mo_contrac_1cc23d_idx",
                    ),
                    models.Index(
                        fields=["requested_by", "-created_at"],
                        name="contract_mo_request_1a382d_idx",
                    ),
                ],
            },
        ),
    ]
