# Generated by Django 4.2.7 on 2025-12-08 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contracts", "0015_alter_landlordcontrolledcontract_current_state_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeudorAuthToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Token seguro para acceder a la página de autenticación",
                        max_length=128,
                        unique=True,
                        verbose_name="Token Único",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash del token para verificación segura",
                        max_length=64,
                        unique=True,
                        verbose_name="Hash del Token",
                    ),
                ),
                (
                    "codeudor_name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Codeudor"
                    ),
                ),
                (
                    "codeudor_email",
                    models.EmailField(
                        max_length=254, verbose_name="Email del Codeudor"
                    ),
                ),
                (
                    "codeudor_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono del Codeudor"
                    ),
                ),
                (
                    "codeudor_document_type",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("CE", "Cédula de Extranjería"),
                            ("PP", "Pasaporte"),
                            ("TI", "Tarjeta de Identidad"),
                            ("NIT", "NIT"),
                        ],
                        default="CC",
                        max_length=10,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "codeudor_document_number",
                    models.CharField(max_length=50, verbose_name="Número de Documento"),
                ),
                (
                    "codeudor_type",
                    models.CharField(
                        choices=[
                            ("codeudor_salario", "Codeudor con Salario"),
                            ("codeudor_finca_raiz", "Codeudor con Finca Raíz"),
                        ],
                        default="codeudor_salario",
                        max_length=30,
                        verbose_name="Tipo de Codeudor",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente de Envío"),
                            ("sent", "Invitación Enviada"),
                            ("accessed", "Link Accedido"),
                            ("in_progress", "Biometría en Progreso"),
                            ("completed", "Completado Exitosamente"),
                            ("expired", "Expirado"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Enviado"),
                ),
                (
                    "accessed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Accedido"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completado"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Expira"),
                ),
                (
                    "biometric_session_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de la sesión de autenticación biométrica",
                        max_length=100,
                        verbose_name="ID de Sesión Biométrica",
                    ),
                ),
                (
                    "biometric_data",
                    models.JSONField(
                        default=dict,
                        help_text="Datos de la autenticación biométrica completada",
                        verbose_name="Datos Biométricos",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP de Acceso"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "access_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Número de Accesos"
                    ),
                ),
                (
                    "personal_message",
                    models.TextField(
                        blank=True,
                        help_text="Mensaje personalizado del arrendador para el codeudor",
                        verbose_name="Mensaje Personal",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codeudor_auth_tokens",
                        to="contracts.landlordcontrolledcontract",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_codeudor_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "guarantee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Garantía específica del codeudor (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_tokens",
                        to="contracts.landlordcontractguarantee",
                        verbose_name="Garantía",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Autenticación de Codeudor",
                "verbose_name_plural": "Tokens de Autenticación de Codeudores",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="contracts_c_token_6bcdb3_idx"),
                    models.Index(
                        fields=["token_hash"], name="contracts_c_token_h_c338b2_idx"
                    ),
                    models.Index(
                        fields=["contract", "status"],
                        name="contracts_c_contrac_01d719_idx",
                    ),
                    models.Index(
                        fields=["codeudor_email"], name="contracts_c_codeudo_aff2f2_idx"
                    ),
                ],
            },
        ),
    ]
