# Generated by Django 4.2.7 on 2025-12-08 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contracts", "0016_codeudorauthtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractTypeTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("rental_urban", "Arrendamiento de Vivienda Urbana"),
                            ("rental_commercial", "Arrendamiento de Local Comercial"),
                            ("rental_room", "Arrendamiento de Habitación"),
                            ("rental_rural", "Arrendamiento de Inmueble Rural"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Tipo de Contrato",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ej: Contrato de Arrendamiento de Vivienda Urbana - Ley 820 de 2003",
                        max_length=200,
                        verbose_name="Nombre Descriptivo",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada de cuándo usar esta plantilla",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar para deshabilitar esta plantilla",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "last_reviewed",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de última revisión por el administrador legal",
                        null=True,
                        verbose_name="Última Revisión Admin",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Contrato",
                "verbose_name_plural": "Plantillas de Contratos",
                "ordering": ["contract_type"],
            },
        ),
        migrations.CreateModel(
            name="EditableContractClause",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "clause_number",
                    models.PositiveIntegerField(
                        help_text="Número secuencial (1-34 para cláusulas estándar)",
                        verbose_name="Número de Cláusula",
                    ),
                ),
                (
                    "ordinal_text",
                    models.CharField(
                        help_text="Ej: PRIMERA, SEGUNDA, TERCERA...",
                        max_length=50,
                        verbose_name="Texto Ordinal",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Ej: OBJETO, PRECIO, TÉRMINO...",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Use {variable} para insertar datos dinámicos. Ej: {property_address}, {monthly_rent}",
                        verbose_name="Contenido con Variables",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("mandatory", "Obligatoria por Ley"),
                            ("standard", "Estándar"),
                            ("optional", "Opcional"),
                            ("guarantee", "Garantías"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "contract_types",
                    models.JSONField(
                        default=list,
                        help_text="Lista de tipos de contrato donde aplica esta cláusula",
                        verbose_name="Tipos de Contrato Aplicables",
                    ),
                ),
                (
                    "legal_reference",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Art. 1973 Código Civil, Ley 820 de 2003",
                        max_length=200,
                        verbose_name="Referencia Legal",
                    ),
                ),
                (
                    "allowed_variables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de variables que se pueden usar en esta cláusula",
                        verbose_name="Variables Permitidas",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Se incrementa automáticamente al editar",
                        verbose_name="Versión",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar para ocultar sin eliminar",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Modificación"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_clauses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cláusula Editable",
                "verbose_name_plural": "Cláusulas Editables",
                "ordering": ["clause_number"],
                "unique_together": {("clause_number", "version")},
            },
        ),
        migrations.CreateModel(
            name="TemplateClauseAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Número de orden (1, 2, 3...)",
                        verbose_name="Orden en Plantilla",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="Si es obligatoria, siempre se incluye en el contrato",
                        verbose_name="Obligatoria",
                    ),
                ),
                (
                    "clause",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contracts.editablecontractclause",
                        verbose_name="Cláusula",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contracts.contracttypetemplate",
                        verbose_name="Plantilla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de Cláusula",
                "verbose_name_plural": "Asignaciones de Cláusulas",
                "ordering": ["order"],
                "unique_together": {("template", "order"), ("template", "clause")},
            },
        ),
        migrations.AddField(
            model_name="contracttypetemplate",
            name="clauses",
            field=models.ManyToManyField(
                through="contracts.TemplateClauseAssignment",
                to="contracts.editablecontractclause",
                verbose_name="Cláusulas",
            ),
        ),
        migrations.AddField(
            model_name="contracttypetemplate",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_templates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Revisado por",
            ),
        ),
        migrations.CreateModel(
            name="ClauseVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(verbose_name="Número de Versión"),
                ),
                (
                    "content_snapshot",
                    models.TextField(verbose_name="Contenido en esta Versión"),
                ),
                (
                    "title_snapshot",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Título en esta Versión",
                    ),
                ),
                (
                    "change_reason",
                    models.TextField(
                        blank=True,
                        help_text="Motivo de la modificación (para auditoría legal)",
                        verbose_name="Razón del Cambio",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha del Cambio"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificado por",
                    ),
                ),
                (
                    "clause",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="contracts.editablecontractclause",
                        verbose_name="Cláusula",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versión de Cláusula",
                "verbose_name_plural": "Versiones de Cláusulas",
                "ordering": ["-version_number"],
                "unique_together": {("clause", "version_number")},
            },
        ),
    ]
