# Generated by Django 4.2.7 on 2025-12-08 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contracts", "0017_editable_clauses_molecular_control"),
    ]

    operations = [
        migrations.AddField(
            model_name="landlordcontrolledcontract",
            name="admin_review_notes",
            field=models.TextField(
                blank=True,
                help_text="Comentarios del administrador durante la revisión",
                verbose_name="Notas de revisión Admin",
            ),
        ),
        migrations.AddField(
            model_name="landlordcontrolledcontract",
            name="admin_reviewed",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el contrato ha sido revisado y aprobado por el administrador",
                verbose_name="Revisado por Admin",
            ),
        ),
        migrations.AddField(
            model_name="landlordcontrolledcontract",
            name="admin_reviewed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha en que el administrador aprobó el borrador",
                null=True,
                verbose_name="Fecha de revisión Admin",
            ),
        ),
        migrations.AddField(
            model_name="landlordcontrolledcontract",
            name="admin_reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_contracts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Revisado por (Admin)",
            ),
        ),
        migrations.AlterField(
            model_name="landlordcontrolledcontract",
            name="current_state",
            field=models.CharField(
                choices=[
                    ("PENDING_ADMIN_REVIEW", "Pendiente Revisión Admin"),
                    ("DRAFT", "Borrador del Arrendador"),
                    ("LANDLORD_COMPLETING", "Arrendador Completando Datos"),
                    ("TENANT_INVITED", "Arrendatario Invitado"),
                    ("TENANT_REVIEWING", "En Revisión por Arrendatario"),
                    (
                        "MODIFICATION_REQUESTED",
                        "Modificación Solicitada por Arrendatario",
                    ),
                    ("UNDER_MODIFICATION", "Arrendador Modificando Borrador"),
                    ("OBJECTIONS_PENDING", "Objeciones Pendientes de Respuesta"),
                    ("NEGOTIATION_IN_PROGRESS", "Negociación en Progreso"),
                    ("APPROVED_BY_TENANT", "Aprobado por Arrendatario"),
                    ("REJECTED_BY_TENANT", "Rechazado por Arrendatario"),
                    ("REJECTED_BY_LANDLORD", "Solicitud de Modificación Rechazada"),
                    ("TENANT_DATA_PENDING", "Esperando Datos del Arrendatario"),
                    (
                        "TENANT_AUTHENTICATION",
                        "Arrendatario en Proceso de Autenticación",
                    ),
                    ("TENANT_SIGNED", "Firmado por Arrendatario"),
                    (
                        "LANDLORD_AUTHENTICATION",
                        "Arrendador en Proceso de Autenticación",
                    ),
                    ("LANDLORD_SIGNED", "Firmado por Arrendador"),
                    ("READY_TO_PUBLISH", "Listo para Publicar"),
                    ("PUBLISHED", "Publicado - Vida Jurídica"),
                    ("ACTIVE", "Contrato Activo"),
                    ("EXPIRED", "Vencido"),
                    ("TERMINATED", "Terminado"),
                    ("CANCELLED", "Cancelado"),
                ],
                default="PENDING_ADMIN_REVIEW",
                max_length=30,
                verbose_name="Estado actual",
            ),
        ),
    ]
