# Generated by Django 4.2.7 on 2025-12-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0018_admin_review_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="editablecontractclause",
            name="has_paragraph",
            field=models.BooleanField(
                default=False,
                help_text="Marcar para agregar un parágrafo a esta cláusula",
                verbose_name="Tiene Parágrafo",
            ),
        ),
        migrations.AddField(
            model_name="editablecontractclause",
            name="paragraph_text",
            field=models.TextField(
                blank=True,
                help_text="Texto del parágrafo. Puede usar {variables} igual que en el contenido principal.",
                verbose_name="Texto del Parágrafo",
            ),
        ),
    ]
