# Generated by Django 4.2.7 on 2025-12-09 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contracts", "0019_add_paragraph_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="landlordcontrolledcontract",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="⚠️ INMUTABLE: True después de autenticación biométrica completa. No se puede editar.",
                verbose_name="Bloqueado",
            ),
        ),
        migrations.AddField(
            model_name="landlordcontrolledcontract",
            name="last_return_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha de la última devolución por parte del arrendatario",
                null=True,
                verbose_name="Última fecha de devolución",
            ),
        ),
        migrations.AddField(
            model_name="landlordcontrolledcontract",
            name="locked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp exacto del momento de bloqueo",
                null=True,
                verbose_name="Fecha de bloqueo",
            ),
        ),
        migrations.AddField(
            model_name="landlordcontrolledcontract",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario cuya autenticación biométrica activó el bloqueo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_contracts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Bloqueado por",
            ),
        ),
        migrations.AddField(
            model_name="landlordcontrolledcontract",
            name="locked_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("biometric_complete", "Autenticación Biométrica Completada"),
                    ("manual_admin_lock", "Bloqueo Manual por Administrador"),
                    ("legal_dispute", "Disputa Legal en Curso"),
                    ("court_order", "Orden Judicial"),
                ],
                help_text="Motivo por el cual el contrato fue bloqueado",
                max_length=100,
                verbose_name="Razón de bloqueo",
            ),
        ),
        migrations.AddField(
            model_name="landlordcontrolledcontract",
            name="review_cycle_count",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Número de veces que el contrato ha pasado por revisión del abogado",
                verbose_name="Ciclos de revisión",
            ),
        ),
        migrations.AddField(
            model_name="landlordcontrolledcontract",
            name="tenant_return_notes",
            field=models.TextField(
                blank=True,
                help_text="Comentarios del arrendatario al devolver el contrato para corrección",
                verbose_name="Notas de devolución del arrendatario",
            ),
        ),
        migrations.AlterField(
            model_name="landlordcontrolledcontract",
            name="current_state",
            field=models.CharField(
                choices=[
                    ("PENDING_ADMIN_REVIEW", "Pendiente Revisión Admin"),
                    ("DRAFT", "Borrador del Arrendador"),
                    ("LANDLORD_COMPLETING", "Arrendador Completando Datos"),
                    ("TENANT_INVITED", "Arrendatario Invitado"),
                    ("TENANT_REVIEWING", "En Revisión por Arrendatario"),
                    ("TENANT_RETURNED", "Devuelto por Arrendatario"),
                    ("LANDLORD_CORRECTING", "Arrendador Corrigiendo"),
                    ("RE_PENDING_ADMIN", "Re-enviado a Revisión Admin"),
                    (
                        "MODIFICATION_REQUESTED",
                        "Modificación Solicitada por Arrendatario",
                    ),
                    ("UNDER_MODIFICATION", "Arrendador Modificando Borrador"),
                    ("OBJECTIONS_PENDING", "Objeciones Pendientes de Respuesta"),
                    ("NEGOTIATION_IN_PROGRESS", "Negociación en Progreso"),
                    ("APPROVED_BY_TENANT", "Aprobado por Arrendatario"),
                    ("REJECTED_BY_TENANT", "Rechazado por Arrendatario"),
                    ("REJECTED_BY_LANDLORD", "Solicitud de Modificación Rechazada"),
                    ("TENANT_DATA_PENDING", "Esperando Datos del Arrendatario"),
                    (
                        "TENANT_AUTHENTICATION",
                        "Arrendatario en Proceso de Autenticación",
                    ),
                    ("TENANT_SIGNED", "Firmado por Arrendatario"),
                    (
                        "LANDLORD_AUTHENTICATION",
                        "Arrendador en Proceso de Autenticación",
                    ),
                    ("LANDLORD_SIGNED", "Firmado por Arrendador"),
                    ("READY_TO_PUBLISH", "Listo para Publicar"),
                    ("PUBLISHED", "Publicado - Vida Jurídica"),
                    ("ACTIVE", "Contrato Activo"),
                    ("EXPIRED", "Vencido"),
                    ("TERMINATED", "Terminado"),
                    ("CANCELLED", "Cancelado"),
                ],
                default="PENDING_ADMIN_REVIEW",
                max_length=30,
                verbose_name="Estado actual",
            ),
        ),
    ]
