# Generated by Django 4.2.7 on 2026-03-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0020_circular_workflow_immutability"),
    ]

    operations = [
        migrations.AddField(
            model_name="landlordcontrolledcontract",
            name="admin_review_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha máxima para que el admin revise el contrato (5 días hábiles)",
                null=True,
                verbose_name="Fecha límite de revisión",
            ),
        ),
        migrations.AddField(
            model_name="landlordcontrolledcontract",
            name="admin_review_escalated",
            field=models.BooleanField(
                default=False,
                help_text="True si el plazo de revisión venció y fue escalado",
                verbose_name="Revisión escalada",
            ),
        ),
    ]
