# Generated by Django 4.2.7 on 2026-03-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0021_landlordcontrolledcontract_admin_review_deadline_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["status", "-created_at"], name="idx_contract_status_date"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["primary_party", "status"], name="idx_contract_primary_status"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["secondary_party", "status"],
                name="idx_contract_secondary_status",
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["property", "status"], name="idx_contract_property_status"
            ),
        ),
    ]
