# Generated by Django 4.2.7 on 2026-04-18 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contracts", "0022_contract_idx_contract_status_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractworkflowhistory",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_actions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Realizado por",
            ),
        ),
        migrations.AlterField(
            model_name="contractworkflowhistory",
            name="user_role",
            field=models.CharField(
                choices=[
                    ("landlord", "Arrendador"),
                    ("tenant", "Arrendatario"),
                    ("system", "Sistema"),
                    ("admin", "Administrador"),
                ],
                default="system",
                max_length=20,
                verbose_name="Rol del usuario",
            ),
        ),
    ]
