# Generated by Django 5.2.3 on 2025-06-28 03:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('communication', 'Comunicación'), ('reliability', 'Confiabilidad'), ('cleanliness', 'Limpieza'), ('punctuality', 'Puntualidad'), ('professionalism', 'Profesionalismo'), ('property_condition', 'Estado de la Propiedad'), ('payment_timeliness', 'Puntualidad de Pagos'), ('responsiveness', 'Capacidad de Respuesta'), ('overall', 'Calificación General')], max_length=30, verbose_name='Categoría')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Puntuación')),
                ('notes', models.TextField(blank=True, max_length=500, verbose_name='Notas específicas')),
            ],
            options={
                'verbose_name': 'Calificación por Categoría',
                'verbose_name_plural': 'Calificaciones por Categorías',
            },
        ),
        migrations.CreateModel(
            name='RatingInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviada'), ('completed', 'Completada'), ('expired', 'Expirada'), ('declined', 'Declinada')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('invitation_token', models.CharField(max_length=100, unique=True, verbose_name='Token de invitación')),
            ],
            options={
                'verbose_name': 'Invitación de Calificación',
                'verbose_name_plural': 'Invitaciones de Calificación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RatingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fake', 'Calificación Falsa'), ('spam', 'Spam'), ('inappropriate', 'Contenido Inapropiado'), ('personal_attack', 'Ataque Personal'), ('discriminatory', 'Contenido Discriminatorio'), ('off_topic', 'Fuera de Tema'), ('other', 'Otro')], max_length=20, verbose_name='Razón del reporte')),
                ('description', models.TextField(max_length=1000, verbose_name='Descripción detallada')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('under_review', 'En Revisión'), ('resolved', 'Resuelto'), ('dismissed', 'Desestimado')], default='pending', max_length=20, verbose_name='Estado')),
                ('resolution_notes', models.TextField(blank=True, max_length=1000, verbose_name='Notas de resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
            ],
            options={
                'verbose_name': 'Reporte de Calificación',
                'verbose_name_plural': 'Reportes de Calificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RatingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(max_length=1500, verbose_name='Respuesta')),
                ('is_public', models.BooleanField(default=True, verbose_name='Respuesta pública')),
                ('is_flagged', models.BooleanField(default=False, verbose_name='Marcada para revisión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Respuesta a Calificación',
                'verbose_name_plural': 'Respuestas a Calificaciones',
            },
        ),
        migrations.CreateModel(
            name='UserRatingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ratings_received', models.PositiveIntegerField(default=0, verbose_name='Total de calificaciones recibidas')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Calificación promedio')),
                ('ratings_distribution', models.JSONField(default=dict, help_text='Conteo de calificaciones por número de estrellas', verbose_name='Distribución de calificaciones')),
                ('category_averages', models.JSONField(default=dict, help_text='Promedio de calificaciones por categoría', verbose_name='Promedios por categoría')),
                ('badges', models.JSONField(default=list, help_text='Lista de badges basados en calificaciones', verbose_name='Badges obtenidos')),
                ('landlord_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Calificación como arrendador')),
                ('tenant_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Calificación como arrendatario')),
                ('service_provider_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Calificación como prestador de servicios')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Perfil de Calificaciones',
                'verbose_name_plural': 'Perfiles de Calificaciones',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating_type', models.CharField(choices=[('landlord_to_tenant', 'Arrendador a Arrendatario'), ('tenant_to_landlord', 'Arrendatario a Arrendador'), ('client_to_service_provider', 'Cliente a Prestador de Servicios'), ('service_provider_to_client', 'Prestador de Servicios a Cliente'), ('general', 'General')], max_length=30, verbose_name='Tipo de calificación')),
                ('overall_rating', models.PositiveIntegerField(help_text='Escala de 1 a 10 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Calificación general')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título de la reseña')),
                ('review_text', models.TextField(blank=True, max_length=2000, verbose_name='Comentarios')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Reseña anónima')),
                ('is_public', models.BooleanField(default=True, verbose_name='Reseña pública')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Reseña verificada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_flagged', models.BooleanField(default=False, verbose_name='Marcada para revisión')),
                ('moderation_status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20, verbose_name='Estado de moderación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='contracts.contract')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='properties.property')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
