# Generated by Django 5.2.3 on 2025-06-15 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_initial'),
        ('ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='reviewee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratingcategory',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_ratings', to='ratings.rating'),
        ),
        migrations.AddField(
            model_name='ratinginvitation',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_invitations', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='ratinginvitation',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_invitations_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratinginvitation',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_invitations_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratinginvitation',
            name='resulting_rating',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation', to='ratings.rating'),
        ),
        migrations.AddField(
            model_name='ratingreport',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ratings.rating'),
        ),
        migrations.AddField(
            model_name='ratingreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_reports_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratingreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_reports_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratingresponse',
            name='rating',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='ratings.rating'),
        ),
        migrations.AddField(
            model_name='ratingresponse',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userratingprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('reviewer', 'reviewee', 'contract')},
        ),
        migrations.AlterUniqueTogether(
            name='ratingcategory',
            unique_together={('rating', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='ratinginvitation',
            unique_together={('contract', 'inviter', 'invitee')},
        ),
        migrations.AlterUniqueTogether(
            name='ratingreport',
            unique_together={('rating', 'reporter')},
        ),
    ]
