# Generated by Django 4.2.7 on 2026-04-18 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_bio_1_9_3_servicerequest_fks"),
        ("ratings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="service_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Vincula la calificación a la orden de servicio facturada.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ratings",
                to="services.serviceorder",
                verbose_name="Orden de servicio",
            ),
        ),
    ]
