# Generated by Django 4.2.7 on 2026-04-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0003_bio_1_9_4_rating_service_order"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("contract__isnull", False), ("service_order__isnull", True)
                ),
                fields=("reviewer", "reviewee", "contract"),
                name="uniq_rating_per_contract",
            ),
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                condition=models.Q(("service_order__isnull", False)),
                fields=("reviewer", "reviewee", "service_order"),
                name="uniq_rating_per_service_order",
            ),
        ),
    ]
