# Generated by Django 4.2.7 on 2025-07-20 20:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Servicio')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('short_description', models.CharField(help_text='Descripción breve para las tarjetas', max_length=200, verbose_name='Descripción Corta')),
                ('full_description', models.TextField(help_text='Descripción detallada del servicio', verbose_name='Descripción Completa')),
                ('pricing_type', models.CharField(choices=[('fixed', 'Precio Fijo'), ('hourly', 'Por Hora'), ('consultation', 'Consulta'), ('quote', 'Bajo Cotización')], default='quote', max_length=20, verbose_name='Tipo de Precio')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio en COP (opcional)', max_digits=10, null=True, verbose_name='Precio Base')),
                ('price_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Mínimo')),
                ('price_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Máximo')),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Medio'), ('hard', 'Difícil'), ('expert', 'Experto')], default='medium', max_length=20, verbose_name='Dificultad')),
                ('estimated_duration', models.CharField(blank=True, help_text="Ej: '2-4 horas', '1 día', '1-2 semanas'", max_length=100, verbose_name='Duración Estimada')),
                ('requirements', models.TextField(blank=True, help_text='Que necesita el cliente para este servicio', verbose_name='Requisitos')),
                ('provider_info', models.TextField(blank=True, help_text='Información sobre quien ofrece este servicio', verbose_name='Información del Proveedor')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto')),
                ('popularity_score', models.PositiveIntegerField(default=0, help_text='Mayor número = más popular', verbose_name='Puntuación de Popularidad')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('requests_count', models.PositiveIntegerField(default=0, verbose_name='Solicitudes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('is_most_requested', models.BooleanField(default=False, verbose_name='Más Solicitado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-popularity_score', '-is_featured', '-is_most_requested', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon_name', models.CharField(default='Build', help_text="Nombre del icono de Material-UI (ej: 'Build', 'AccountBalance', 'Security')", max_length=50, verbose_name='Icono (Material-UI)')),
                ('color', models.CharField(default='#2196F3', help_text='Color hexadecimal (ej: #2196F3)', max_length=7, verbose_name='Color')),
                ('order', models.PositiveIntegerField(default=0, help_text='Menor número aparece primero', verbose_name='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicios',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requester_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('requester_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('requester_phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('message', models.TextField(help_text='Detalles de lo que necesita', verbose_name='Mensaje')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='Fecha Preferida')),
                ('budget_range', models.CharField(blank=True, max_length=100, verbose_name='Presupuesto Estimado')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('contacted', 'Contactado'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas del Administrador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='services.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Solicitud de Servicio',
                'verbose_name_plural': 'Solicitudes de Servicios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/images/', verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto Alternativo')),
                ('is_main', models.BooleanField(default=False, verbose_name='Imagen Principal')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Imagen de Servicio',
                'verbose_name_plural': 'Imágenes de Servicios',
                'ordering': ['-is_main', 'order'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='Categoría'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_active'], name='services_se_categor_b50c86_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_featured', 'is_active'], name='services_se_is_feat_fb2165_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_most_requested', 'is_active'], name='services_se_is_most_2014f8_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['popularity_score'], name='services_se_popular_23a890_idx'),
        ),
    ]
