# Generated by Django 4.2.7 on 2026-03-23 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Período de Prueba"),
                            ("active", "Activa"),
                            ("past_due", "Pago Vencido"),
                            ("suspended", "Suspendida"),
                            ("cancelled", "Cancelada"),
                            ("expired", "Expirada"),
                        ],
                        default="trial",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Fecha de inicio")),
                ("end_date", models.DateTimeField(verbose_name="Fecha de vencimiento")),
                (
                    "trial_end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin del período de prueba"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de cancelación"
                    ),
                ),
                (
                    "next_billing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Próxima fecha de cobro"
                    ),
                ),
                (
                    "auto_renew",
                    models.BooleanField(
                        default=True, verbose_name="Renovación automática"
                    ),
                ),
                (
                    "services_published",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Servicios publicados"
                    ),
                ),
                (
                    "requests_this_month",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Solicitudes este mes"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="Motivo de cancelación"),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Notas admin"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscripción de Servicio",
                "verbose_name_plural": "Suscripciones de Servicios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Nombre del plan"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Mensual"),
                            ("quarterly", "Trimestral"),
                            ("annual", "Anual"),
                        ],
                        default="monthly",
                        max_length=15,
                        verbose_name="Ciclo de facturación",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Precio (COP)"
                    ),
                ),
                (
                    "discount_percentage",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Descuento aplicado sobre el precio base",
                        verbose_name="Descuento (%)",
                    ),
                ),
                (
                    "max_active_services",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Máx. servicios activos"
                    ),
                ),
                (
                    "max_monthly_requests",
                    models.PositiveIntegerField(
                        default=20, verbose_name="Máx. solicitudes/mes"
                    ),
                ),
                (
                    "featured_listing",
                    models.BooleanField(
                        default=False, verbose_name="Listado destacado"
                    ),
                ),
                (
                    "priority_in_search",
                    models.BooleanField(
                        default=False, verbose_name="Prioridad en búsquedas"
                    ),
                ),
                (
                    "verified_badge",
                    models.BooleanField(default=False, verbose_name="Badge verificado"),
                ),
                (
                    "access_to_analytics",
                    models.BooleanField(
                        default=False, verbose_name="Acceso a analíticas"
                    ),
                ),
                (
                    "direct_messaging",
                    models.BooleanField(
                        default=True, verbose_name="Mensajería directa"
                    ),
                ),
                (
                    "payment_gateway_access",
                    models.BooleanField(
                        default=False, verbose_name="Pasarela de pagos propia"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "is_recommended",
                    models.BooleanField(
                        default=False,
                        help_text='Mostrar badge "Recomendado" en la UI',
                        verbose_name="Recomendado",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Orden de visualización"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de Suscripción",
                "verbose_name_plural": "Planes de Suscripción",
                "ordering": ["sort_order", "price"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionBillingHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        verbose_name="Monto cobrado (COP)",
                    ),
                ),
                ("billing_date", models.DateField(verbose_name="Fecha de cobro")),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Método de pago"
                    ),
                ),
                (
                    "transaction_ref",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Referencia de transacción",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("paid", "Pagado"),
                            ("failed", "Fallido"),
                            ("refunded", "Reembolsado"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_history",
                        to="services.servicesubscription",
                        verbose_name="Suscripción",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Facturación",
                "verbose_name_plural": "Historial de Facturación",
                "ordering": ["-billing_date"],
            },
        ),
        migrations.AddField(
            model_name="servicesubscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="services.subscriptionplan",
                verbose_name="Plan",
            ),
        ),
        migrations.AddField(
            model_name="servicesubscription",
            name="service_provider",
            field=models.OneToOneField(
                limit_choices_to={"user_type": "service_provider"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_subscription",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Prestador de servicios",
            ),
        ),
    ]
