# Generated by Django 4.2.7 on 2026-04-16 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0002_servicesubscription_subscriptionplan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "service_provider"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="provided_services",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Proveedor",
            ),
        ),
    ]
