# Generated by Django 4.2.7 on 2026-04-16 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0008_paymentorder"),
        ("services", "0003_svc02_service_provider_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Descripción del trabajo"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("sent", "Enviada al cliente"),
                            ("accepted", "Aceptada (lista para pago)"),
                            ("paid", "Pagada"),
                            ("rejected", "Rechazada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de pago esperada"
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, verbose_name="Notas internas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_orders_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cliente (arrendador o arrendatario)",
                    ),
                ),
                (
                    "payment_order",
                    models.OneToOneField(
                        blank=True,
                        help_text="Generada cuando el cliente acepta.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_order",
                        to="payments.paymentorder",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "service_provider"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_orders_issued",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Prestador",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Catálogo de referencia (opcional, puede ser servicio ad-hoc).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Servicio",
                "verbose_name_plural": "Órdenes de Servicio",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServicePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto pagado"
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("wompi", "Wompi"),
                            ("pse", "PSE"),
                            ("manual", "Manual / efectivo"),
                        ],
                        max_length=20,
                        verbose_name="Pasarela",
                    ),
                ),
                ("paid_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Referencia"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="services.serviceorder",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Transaction de la pasarela cuando el webhook reconcilia.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_payments",
                        to="payments.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago de Servicio",
                "verbose_name_plural": "Pagos de Servicio",
                "ordering": ["-paid_at"],
            },
        ),
        migrations.AddIndex(
            model_name="serviceorder",
            index=models.Index(
                fields=["provider", "status"], name="services_se_provide_ee7fba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceorder",
            index=models.Index(
                fields=["client", "status"], name="services_se_client__aa02b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceorder",
            index=models.Index(
                fields=["status", "created_at"], name="services_se_status_a7cfef_idx"
            ),
        ),
    ]
