# Generated by Django 4.2.7 on 2026-04-18 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0024_bio_1_9_2_backfill_workflow_history"),
        ("properties", "0010_property_idx_property_status_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0004_serviceorder_servicepayment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                help_text="Contrato de arrendamiento que origina el servicio (ej: mantenimiento bajo contrato)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="catalog_service_requests",
                to="contracts.contract",
                verbose_name="Contrato relacionado",
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="property",
            field=models.ForeignKey(
                blank=True,
                help_text="Propiedad sobre la que recae el servicio (si aplica)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="catalog_service_requests",
                to="properties.property",
                verbose_name="Propiedad relacionada",
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="requester",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario autenticado que creó la solicitud (null para anónimas)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="catalog_service_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario solicitante",
            ),
        ),
    ]
