# Generated by Django 4.2.7 on 2026-04-18 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0005_bio_1_9_3_servicerequest_fks"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceOrderHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Crear orden"),
                            ("STATE_CHANGE", "Cambio de estado"),
                            ("SEND", "Enviada al cliente"),
                            ("ACCEPT", "Aceptada"),
                            ("REJECT", "Rechazada"),
                            ("CANCEL", "Cancelada"),
                            ("PAY", "Pagada"),
                            ("UPDATE", "Actualización"),
                            ("SYSTEM_ACTION", "Acción del sistema"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de acción",
                    ),
                ),
                (
                    "action_description",
                    models.CharField(
                        help_text="Texto legible para auditoría.",
                        max_length=500,
                        verbose_name="Descripción de la acción",
                    ),
                ),
                (
                    "user_role",
                    models.CharField(
                        choices=[
                            ("service_provider", "Prestador"),
                            ("client", "Cliente"),
                            ("system", "Sistema"),
                            ("admin", "Administrador"),
                        ],
                        default="system",
                        max_length=20,
                        verbose_name="Rol del usuario",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Estado anterior"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Estado nuevo"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Información adicional: monto, notas, payment_order_id, etc.",
                        verbose_name="Metadatos",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_entries",
                        to="services.serviceorder",
                        verbose_name="Orden de servicio",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null cuando lo ejecuta el sistema (signal / cron).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_order_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Realizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Orden de Servicio",
                "verbose_name_plural": "Historial de Órdenes de Servicio",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["order", "-timestamp"],
                        name="services_se_order_i_1f89ca_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-timestamp"],
                        name="services_se_action__3958da_idx",
                    ),
                ],
            },
        ),
    ]
