# Generated by Django 5.2.3 on 2025-06-15 20:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(max_length=2000, verbose_name='Descripción')),
                ('property_type', models.CharField(choices=[('apartment', 'Apartamento'), ('house', 'Casa'), ('studio', 'Estudio'), ('penthouse', 'Penthouse'), ('townhouse', 'Casa en Condominio'), ('commercial', 'Comercial'), ('office', 'Oficina'), ('warehouse', 'Bodega'), ('land', 'Terreno'), ('room', 'Habitación')], max_length=20, verbose_name='Tipo de propiedad')),
                ('listing_type', models.CharField(choices=[('rent', 'Renta'), ('sale', 'Venta'), ('both', 'Ambos')], default='rent', max_length=10, verbose_name='Tipo de listado')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('rented', 'Rentada'), ('maintenance', 'En Mantenimiento'), ('pending', 'Pendiente'), ('inactive', 'Inactiva')], default='available', max_length=20, verbose_name='Estado')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Estado/Provincia')),
                ('country', models.CharField(default='México', max_length=100, verbose_name='País')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Código postal')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('bedrooms', models.PositiveIntegerField(default=0, verbose_name='Habitaciones')),
                ('bathrooms', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Baños')),
                ('half_bathrooms', models.PositiveIntegerField(default=0, verbose_name='Medios baños')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Área total (m²)')),
                ('built_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Área construida (m²)')),
                ('lot_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Área del terreno (m²)')),
                ('parking_spaces', models.PositiveIntegerField(default=0, verbose_name='Espacios de estacionamiento')),
                ('floors', models.PositiveIntegerField(default=1, verbose_name='Pisos')),
                ('floor_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de piso')),
                ('year_built', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de construcción')),
                ('rent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio de renta mensual')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Precio de venta')),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Depósito de garantía')),
                ('maintenance_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cuota de mantenimiento')),
                ('minimum_lease_term', models.PositiveIntegerField(default=12, verbose_name='Plazo mínimo de renta (meses)')),
                ('maximum_lease_term', models.PositiveIntegerField(blank=True, null=True, verbose_name='Plazo máximo de renta (meses)')),
                ('pets_allowed', models.BooleanField(default=False, verbose_name='Mascotas permitidas')),
                ('smoking_allowed', models.BooleanField(default=False, verbose_name='Fumar permitido')),
                ('furnished', models.BooleanField(default=False, verbose_name='Amueblada')),
                ('utilities_included', models.JSONField(default=list, verbose_name='Servicios incluidos')),
                ('property_features', models.JSONField(default=list, verbose_name='Características de la propiedad')),
                ('nearby_amenities', models.JSONField(default=list, verbose_name='Amenidades cercanas')),
                ('transportation', models.JSONField(default=list, verbose_name='Transporte cercano')),
                ('available_from', models.DateField(blank=True, null=True, verbose_name='Disponible desde')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Número de visualizaciones')),
                ('favorites_count', models.PositiveIntegerField(default=0, verbose_name='Número de favoritos')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Propiedad destacada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('category', models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior'), ('security', 'Seguridad'), ('recreation', 'Recreación'), ('utilities', 'Servicios'), ('parking', 'Estacionamiento'), ('accessibility', 'Accesibilidad')], max_length=20, verbose_name='Categoría')),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono CSS', max_length=50, verbose_name='Icono')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Amenidad',
                'verbose_name_plural': 'Amenidades',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenityRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Amenidad de Propiedad',
                'verbose_name_plural': 'Amenidades de Propiedades',
            },
        ),
        migrations.CreateModel(
            name='PropertyFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de adición')),
            ],
            options={
                'verbose_name': 'Propiedad Favorita',
                'verbose_name_plural': 'Propiedades Favoritas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/images/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('is_main', models.BooleanField(default=False, verbose_name='Imagen principal')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
            ],
            options={
                'verbose_name': 'Imagen de Propiedad',
                'verbose_name_plural': 'Imágenes de Propiedades',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('message', models.TextField(max_length=1000, verbose_name='Mensaje')),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Correo electrónico'), ('phone', 'Teléfono'), ('message', 'Mensaje interno')], default='email', max_length=20, verbose_name='Método de contacto preferido')),
                ('move_in_date', models.DateField(blank=True, null=True, verbose_name='Fecha de mudanza')),
                ('lease_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración de arrendamiento (meses)')),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Presupuesto mínimo')),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Presupuesto máximo')),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('contacted', 'Contactado'), ('viewing_scheduled', 'Visita Programada'), ('closed', 'Cerrada')], default='new', max_length=20, verbose_name='Estado')),
                ('response', models.TextField(blank=True, max_length=1000, verbose_name='Respuesta')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de consulta')),
            ],
            options={
                'verbose_name': 'Consulta de Propiedad',
                'verbose_name_plural': 'Consultas de Propiedades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='properties/videos/', verbose_name='Video')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Descripción')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duración')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='properties/video_thumbnails/', verbose_name='Miniatura')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
            ],
            options={
                'verbose_name': 'Video de Propiedad',
                'verbose_name_plural': 'Videos de Propiedades',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de visualización')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Clave de sesión')),
            ],
            options={
                'verbose_name': 'Visualización de Propiedad',
                'verbose_name_plural': 'Visualizaciones de Propiedades',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
