# Generated by Django 5.2.3 on 2025-06-28 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(limit_choices_to={'user_type': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyamenityrelation',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_relations', to='properties.propertyamenity'),
        ),
        migrations.AddField(
            model_name='propertyamenityrelation',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_relations', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertyfavorite',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertyfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='inquirer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertyview',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_views', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertyview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='propertyamenityrelation',
            unique_together={('property', 'amenity')},
        ),
        migrations.AlterUniqueTogether(
            name='propertyfavorite',
            unique_together={('user', 'property')},
        ),
    ]
