# Generated by Django 5.2.3 on 2025-07-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código postal'),
        ),
    ]
