# Generated by Django 4.2.7 on 2025-07-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyvideo',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de YouTube'),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='properties/videos/', verbose_name='Video'),
        ),
    ]
