# Generated by Django 4.2.7 on 2025-08-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertyvideo_youtube_url_alter_propertyvideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_available_for_workflow',
            field=models.BooleanField(default=True, help_text='False cuando la propiedad está en proceso de contratación (Etapa 3)', verbose_name='Disponible para workflow de contratos'),
        ),
    ]
