# Generated by Django 4.2.7 on 2025-08-15 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_is_available_for_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='properties/documents/', verbose_name='Documento')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Descripción')),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('text', 'Texto'), ('archive', 'Archivo comprimido'), ('audio', 'Audio'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Tipo de documento')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Tamaño del archivo (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME')),
                ('is_public', models.BooleanField(default=True, help_text='Si está disponible para inquilinos', verbose_name='Público')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property')),
            ],
            options={
                'verbose_name': 'Documento de Propiedad',
                'verbose_name_plural': 'Documentos de Propiedades',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
