# Generated by Django 4.2.7 on 2025-08-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertydocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='nearby_amenities',
            field=models.TextField(blank=True, default='', verbose_name='Amenidades cercanas'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_features',
            field=models.TextField(blank=True, default='', verbose_name='Características de la propiedad'),
        ),
        migrations.AlterField(
            model_name='property',
            name='transportation',
            field=models.TextField(blank=True, default='', verbose_name='Transporte cercano'),
        ),
        migrations.AlterField(
            model_name='property',
            name='utilities_included',
            field=models.TextField(blank=True, default='', verbose_name='Servicios incluidos'),
        ),
    ]
