# Generated by Django 4.2.7 on 2025-08-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20250824_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyvideo',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Video de Propiedad', 'verbose_name_plural': 'Videos de Propiedades'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_available_for_workflow',
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='property',
            name='nearby_amenities',
            field=models.JSONField(default=list, verbose_name='Amenidades cercanas'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_features',
            field=models.JSONField(default=list, verbose_name='Características de la propiedad'),
        ),
        migrations.AlterField(
            model_name='property',
            name='transportation',
            field=models.JSONField(default=list, verbose_name='Transporte cercano'),
        ),
        migrations.AlterField(
            model_name='property',
            name='utilities_included',
            field=models.JSONField(default=list, verbose_name='Servicios incluidos'),
        ),
        migrations.DeleteModel(
            name='PropertyDocument',
        ),
    ]
