# Generated by Django 4.2.7 on 2026-03-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0009_alter_propertyvideo_options_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["status", "is_active"], name="idx_property_status_active"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["city", "status"], name="idx_property_city_status"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["landlord", "-created_at"], name="idx_property_landlord_date"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["property_type", "status"], name="idx_property_type_status"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["rent_price"], name="idx_property_rent_price"),
        ),
    ]
