# Generated by Django 4.2.7 on 2025-07-06 17:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_messages', models.PositiveIntegerField(default=0, verbose_name='Total de mensajes')),
                ('average_response_time', models.DurationField(blank=True, null=True, verbose_name='Tiempo promedio de respuesta')),
                ('first_response_time', models.DurationField(blank=True, null=True, verbose_name='Tiempo de primera respuesta')),
                ('messages_by_initiator', models.PositiveIntegerField(default=0, verbose_name='Mensajes del iniciador')),
                ('messages_by_responder', models.PositiveIntegerField(default=0, verbose_name='Mensajes del respondedor')),
                ('first_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Primer mensaje')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Última actividad')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resuelta')),
                ('resolution_time', models.DurationField(blank=True, null=True, verbose_name='Tiempo de resolución')),
                ('satisfaction_rating', models.PositiveIntegerField(blank=True, help_text='Escala de 1 a 5', null=True, verbose_name='Calificación de satisfacción')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Analítica de Conversación',
                'verbose_name_plural': 'Analíticas de Conversaciones',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('file', 'Archivo'), ('system', 'Sistema'), ('audio', 'Audio')], default='text', max_length=20, verbose_name='Tipo de mensaje')),
                ('content', models.TextField(blank=True, max_length=5000, verbose_name='Contenido')),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido')], default='sent', max_length=20, verbose_name='Estado')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
                ('is_starred', models.BooleanField(default=False, verbose_name='Destacado')),
                ('is_flagged', models.BooleanField(default=False, verbose_name='Marcado')),
                ('is_deleted_by_sender', models.BooleanField(default=False, verbose_name='Eliminado por remitente')),
                ('is_deleted_by_recipient', models.BooleanField(default=False, verbose_name='Eliminado por destinatario')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='message_attachments/', verbose_name='Archivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nombre original')),
                ('file_size', models.PositiveIntegerField(verbose_name='Tamaño (bytes)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='Tipo MIME')),
                ('attachment_type', models.CharField(choices=[('image', 'Imagen'), ('document', 'Documento'), ('audio', 'Audio'), ('video', 'Video'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de archivo')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Descripción')),
                ('is_image', models.BooleanField(default=False, verbose_name='Es imagen')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la carpeta')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Descripción')),
                ('folder_type', models.CharField(choices=[('custom', 'Personalizada'), ('system', 'Sistema')], default='custom', max_length=20, verbose_name='Tipo')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Color')),
                ('is_default', models.BooleanField(default=False, verbose_name='Carpeta por defecto')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Carpeta de Mensajes',
                'verbose_name_plural': 'Carpetas de Mensajes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MessageFolderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de adición')),
            ],
            options={
                'verbose_name': 'Elemento de Carpeta',
                'verbose_name_plural': 'Elementos de Carpetas',
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('laugh', '😂'), ('surprised', '😮'), ('sad', '😢'), ('angry', '😠')], max_length=20, verbose_name='Tipo de reacción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reacción')),
            ],
            options={
                'verbose_name': 'Reacción a Mensaje',
                'verbose_name_plural': 'Reacciones a Mensajes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la plantilla')),
                ('category', models.CharField(choices=[('greeting', 'Saludo'), ('inquiry_response', 'Respuesta a Consulta'), ('appointment', 'Cita'), ('follow_up', 'Seguimiento'), ('closing', 'Cierre'), ('custom', 'Personalizada')], max_length=20, verbose_name='Categoría')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Asunto')),
                ('content', models.TextField(max_length=2000, verbose_name='Contenido')),
                ('variables', models.JSONField(default=list, help_text='Variables que se pueden usar en la plantilla', verbose_name='Variables disponibles')),
                ('is_public', models.BooleanField(default=False, verbose_name='Plantilla pública')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Veces utilizada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Plantilla de Mensaje',
                'verbose_name_plural': 'Plantillas de Mensajes',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('thread_type', models.CharField(choices=[('inquiry', 'Consulta de Propiedad'), ('contract', 'Relacionado a Contrato'), ('service', 'Servicios'), ('support', 'Soporte'), ('general', 'General')], max_length=20, verbose_name='Tipo de conversación')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('archived', 'Archivada'), ('blocked', 'Bloqueada'), ('closed', 'Cerrada')], default='active', max_length=20, verbose_name='Estado')),
                ('is_priority', models.BooleanField(default=False, verbose_name='Prioridad alta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Último mensaje')),
            ],
            options={
                'verbose_name': 'Hilo de Conversación',
                'verbose_name_plural': 'Hilos de Conversación',
                'ordering': ['-last_message_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Participación activa')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Conversación archivada')),
                ('is_muted', models.BooleanField(default=False, verbose_name='Notificaciones silenciadas')),
                ('is_starred', models.BooleanField(default=False, verbose_name='Conversación destacada')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de unión')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='Última lectura')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de archivo')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_participants', to='messaging.messagethread')),
            ],
            options={
                'verbose_name': 'Participante de Conversación',
                'verbose_name_plural': 'Participantes de Conversaciones',
            },
        ),
    ]
