# Generated by Django 4.2.7 on 2026-04-18 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0006_bio_1_9_5_service_order_history"),
        ("messaging", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagethread",
            name="service_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Vincula la conversación a una orden de servicio específica.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="message_threads",
                to="services.serviceorder",
                verbose_name="Orden de servicio",
            ),
        ),
    ]
