# Generated by Django 4.2.7 on 2025-07-20 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_propertyvideo_youtube_url_alter_propertyvideo_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('property_interest', 'Interés en Propiedad'), ('service_request', 'Solicitud de Servicio'), ('contract_signature', 'Firma de Contrato'), ('maintenance_request', 'Solicitud de Mantenimiento'), ('tenant_verification', 'Verificación de Arrendatario'), ('landlord_inquiry', 'Consulta a Arrendador'), ('property_viewing', 'Visita a Propiedad'), ('rent_negotiation', 'Negociación de Renta'), ('lease_renewal', 'Renovación de Contrato'), ('damage_report', 'Reporte de Daños')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('on_hold', 'En Espera')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('response_message', models.TextField(blank=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('request_created', 'Solicitud Creada'), ('request_updated', 'Solicitud Actualizada'), ('request_completed', 'Solicitud Completada'), ('request_rejected', 'Solicitud Rechazada'), ('comment_added', 'Comentario Agregado'), ('due_date_reminder', 'Recordatorio de Fecha Límite'), ('overdue_alert', 'Alerta de Vencimiento')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_notifications', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='requests.baserequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='requests.baserequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='request_attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='requests.baserequest')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('baserequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requests.baserequest')),
                ('service_category', models.CharField(choices=[('cleaning', 'Limpieza'), ('maintenance', 'Mantenimiento'), ('plumbing', 'Plomería'), ('electrical', 'Electricidad'), ('painting', 'Pintura'), ('gardening', 'Jardinería'), ('security', 'Seguridad'), ('moving', 'Mudanza'), ('repair', 'Reparación'), ('installation', 'Instalación')], max_length=50)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('flexible_schedule', models.BooleanField(default=True)),
                ('location_details', models.TextField(blank=True)),
                ('urgency_level', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='properties.property')),
            ],
            bases=('requests.baserequest',),
        ),
        migrations.CreateModel(
            name='PropertyInterestRequest',
            fields=[
                ('baserequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requests.baserequest')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=50)),
                ('preferred_move_in_date', models.DateField(blank=True, null=True)),
                ('lease_duration_months', models.IntegerField(default=12)),
                ('number_of_occupants', models.IntegerField(default=1)),
                ('has_pets', models.BooleanField(default=False)),
                ('pet_details', models.TextField(blank=True)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('has_rental_references', models.BooleanField(default=False)),
                ('has_employment_proof', models.BooleanField(default=False)),
                ('has_credit_check', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_requests', to='properties.property')),
            ],
            bases=('requests.baserequest',),
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('baserequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requests.baserequest')),
                ('maintenance_type', models.CharField(choices=[('emergency', 'Emergencia'), ('routine', 'Rutina'), ('preventive', 'Preventivo'), ('repair', 'Reparación'), ('improvement', 'Mejora')], max_length=20)),
                ('affected_area', models.CharField(max_length=100)),
                ('issue_description', models.TextField()),
                ('photos_uploaded', models.BooleanField(default=False)),
                ('access_instructions', models.TextField(blank=True)),
                ('requires_tenant_presence', models.BooleanField(default=False)),
                ('estimated_duration_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='properties.property')),
            ],
            bases=('requests.baserequest',),
        ),
        migrations.CreateModel(
            name='ContractSignatureRequest',
            fields=[
                ('baserequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requests.baserequest')),
                ('contract_type', models.CharField(max_length=50)),
                ('rental_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lease_start_date', models.DateField()),
                ('lease_end_date', models.DateField()),
                ('landlord_signed', models.BooleanField(default=False)),
                ('tenant_signed', models.BooleanField(default=False)),
                ('landlord_signature_date', models.DateTimeField(blank=True, null=True)),
                ('tenant_signature_date', models.DateTimeField(blank=True, null=True)),
                ('documents_uploaded', models.BooleanField(default=False)),
                ('verification_completed', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='contracts.contract')),
            ],
            bases=('requests.baserequest',),
        ),
        migrations.AddIndex(
            model_name='baserequest',
            index=models.Index(fields=['requester', 'status'], name='requests_ba_request_bee45b_idx'),
        ),
        migrations.AddIndex(
            model_name='baserequest',
            index=models.Index(fields=['assignee', 'status'], name='requests_ba_assigne_cfab5f_idx'),
        ),
        migrations.AddIndex(
            model_name='baserequest',
            index=models.Index(fields=['request_type', 'status'], name='requests_ba_request_e0fe25_idx'),
        ),
        migrations.AddIndex(
            model_name='baserequest',
            index=models.Index(fields=['created_at'], name='requests_ba_created_38ee8e_idx'),
        ),
    ]
