# Generated by Django 4.2.7 on 2025-08-11 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('tomador_cedula_frente', 'Cédula de Ciudadanía - Frente'), ('tomador_cedula_atras', 'Cédula de Ciudadanía - Atrás'), ('tomador_pasaporte', 'Pasaporte'), ('tomador_cedula_extranjeria_frente', 'Cédula de Extranjería - Frente'), ('tomador_cedula_extranjeria_atras', 'Cédula de Extranjería - Atrás'), ('tomador_certificado_laboral', 'Certificado Laboral'), ('tomador_carta_recomendacion', 'Carta de Recomendación'), ('codeudor_cedula_frente', 'Codeudor: Cédula de Ciudadanía - Frente'), ('codeudor_cedula_atras', 'Codeudor: Cédula de Ciudadanía - Atrás'), ('codeudor_pasaporte', 'Codeudor: Pasaporte'), ('codeudor_cedula_extranjeria_frente', 'Codeudor: Cédula de Extranjería - Frente'), ('codeudor_cedula_extranjeria_atras', 'Codeudor: Cédula de Extranjería - Atrás'), ('codeudor_certificado_laboral', 'Codeudor: Certificado Laboral'), ('codeudor_libertad_tradicion', 'Codeudor: Certificado de Libertad y Tradición'), ('otros', 'Otros Documentos')], max_length=50)),
                ('document_file', models.FileField(help_text='Solo archivos PDF permitidos', upload_to='tenant_documents/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Tamaño en bytes')),
                ('other_description', models.CharField(blank=True, help_text='Descripción para documentos tipo "otros"', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('requires_correction', 'Requiere Corrección')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_documents', to='requests.propertyinterestrequest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['property_request', 'document_type'], name='requests_te_propert_cde9c6_idx'), models.Index(fields=['uploaded_by', 'status'], name='requests_te_uploade_285df7_idx'), models.Index(fields=['status', 'uploaded_at'], name='requests_te_status_5c20d1_idx')],
                'unique_together': {('property_request', 'document_type', 'uploaded_by')},
            },
        ),
    ]
