# Generated by Django 4.2.7 on 2025-08-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_tenantdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinterestrequest',
            name='workflow_data',
            field=models.JSONField(blank=True, default=dict, help_text='Datos específicos del workflow como fechas de visita, documentos, etc.'),
        ),
        migrations.AddField(
            model_name='propertyinterestrequest',
            name='workflow_stage',
            field=models.IntegerField(choices=[(1, 'Etapa 1: Visita'), (2, 'Etapa 2: Documentos'), (3, 'Etapa 3: Contrato')], default=1),
        ),
        migrations.AddField(
            model_name='propertyinterestrequest',
            name='workflow_status',
            field=models.CharField(choices=[('visit_scheduled', 'Visita Programada'), ('visit_completed', 'Visita Completada'), ('documents_pending', 'Documentos Pendientes'), ('documents_review', 'Documentos en Revisión'), ('documents_approved', 'Documentos Aprobados'), ('contract_ready', 'Contrato Listo'), ('contract_signed', 'Contrato Firmado'), ('completed', 'Proceso Completado')], default='visit_scheduled', max_length=30),
        ),
        migrations.AddField(
            model_name='propertyinterestrequest',
            name='workflow_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
