# Generated by Django 4.2.7 on 2025-08-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_propertyinterestrequest_workflow_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdocument',
            name='document_type',
            field=models.CharField(choices=[('tomador_cedula_ciudadania', 'Cédula de Ciudadanía'), ('tomador_pasaporte', 'Pasaporte'), ('tomador_cedula_extranjeria', 'Cédula de Extranjería'), ('tomador_certificado_laboral', 'Certificado Laboral'), ('tomador_carta_recomendacion', 'Carta de Recomendación'), ('codeudor_cedula_ciudadania', 'Codeudor: Cédula de Ciudadanía'), ('codeudor_pasaporte', 'Codeudor: Pasaporte'), ('codeudor_cedula_extranjeria', 'Codeudor: Cédula de Extranjería'), ('codeudor_certificado_laboral', 'Codeudor: Certificado Laboral'), ('codeudor_libertad_tradicion', 'Codeudor: Certificado de Libertad y Tradición'), ('otros', 'Otros Documentos (Personalizable)'), ('tomador_cedula_frente', 'Cédula de Ciudadanía - Frente (Legacy)'), ('tomador_cedula_atras', 'Cédula de Ciudadanía - Atrás (Legacy)'), ('codeudor_cedula_frente', 'Codeudor: Cédula de Ciudadanía - Frente (Legacy)'), ('codeudor_cedula_atras', 'Codeudor: Cédula de Ciudadanía - Atrás (Legacy)'), ('tomador_cedula_extranjeria_frente', 'Cédula de Extranjería - Frente (Legacy)'), ('tomador_cedula_extranjeria_atras', 'Cédula de Extranjería - Atrás (Legacy)'), ('codeudor_cedula_extranjeria_frente', 'Codeudor: Cédula de Extranjería - Frente (Legacy)'), ('codeudor_cedula_extranjeria_atras', 'Codeudor: Cédula de Extranjería - Atrás (Legacy)')], max_length=50),
        ),
    ]
