# Generated by Django 4.2.7 on 2025-09-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_update_document_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdocument',
            name='document_file',
            field=models.FileField(
                max_length=255,
                upload_to='tenant_documents/%Y/%m/',
                help_text='Solo archivos PDF permitidos'
            ),
        ),
    ]
