# Generated by Django 4.2.7 on 2025-11-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requests", "0008_alter_tenantdocument_match_request_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantdocument",
            name="document_type",
            field=models.CharField(
                help_text="Tipo de documento. Puede ser estático o dinámico (otros_timestamp)",
                max_length=100,
            ),
        ),
    ]
