# Generated by Django 4.2.7 on 2025-12-09 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("requests", "0009_alter_tenantdocument_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantdocument",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="Documento bloqueado post-autenticación biométrica",
            ),
        ),
        migrations.AddField(
            model_name="tenantdocument",
            name="locked_at",
            field=models.DateTimeField(
                blank=True, help_text="Fecha y hora del bloqueo", null=True
            ),
        ),
        migrations.AddField(
            model_name="tenantdocument",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que ejecutó el bloqueo (último en autenticar)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenantdocument",
            name="locked_reason",
            field=models.CharField(
                blank=True,
                help_text="Razón del bloqueo (ej: biometric_complete)",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="DocumentAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "Visualización"),
                            ("download", "Descarga"),
                            ("preview", "Vista Previa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Datos adicionales del acceso (dispositivo, ubicación, etc.)",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="requests.tenantdocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Acceso a Documento",
                "verbose_name_plural": "Logs de Acceso a Documentos",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["document", "timestamp"],
                        name="requests_do_documen_d4857c_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="requests_do_user_id_605e58_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="requests_do_action_23c2a3_idx",
                    ),
                ],
            },
        ),
    ]
