# Generated by Django 4.2.7 on 2025-07-06 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='Arrendador'),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requests', to='properties.property', verbose_name='Propiedad'),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='Arrendatario'),
        ),
        migrations.AddField(
            model_name='matchnotification',
            name='match_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='matching.matchrequest', verbose_name='Solicitud de Match'),
        ),
        migrations.AddField(
            model_name='matchnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='matchcriteria',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_criteria', to=settings.AUTH_USER_MODEL, verbose_name='Arrendatario'),
        ),
        migrations.AddIndex(
            model_name='matchrequest',
            index=models.Index(fields=['status', 'created_at'], name='matching_ma_status_895201_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrequest',
            index=models.Index(fields=['landlord', 'status'], name='matching_ma_landlor_139284_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrequest',
            index=models.Index(fields=['tenant', 'created_at'], name='matching_ma_tenant__621501_idx'),
        ),
        migrations.AddIndex(
            model_name='matchnotification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='matching_ma_user_id_9138d6_idx'),
        ),
        migrations.AddIndex(
            model_name='matchnotification',
            index=models.Index(fields=['notification_type', 'created_at'], name='matching_ma_notific_a75abb_idx'),
        ),
    ]
