# Generated by Django 4.2.7 on 2025-07-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='contract_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de generación del contrato'),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='has_contract',
            field=models.BooleanField(default=False, verbose_name='Tiene contrato'),
        ),
    ]
