# Generated by Django 4.2.7 on 2025-08-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_matchrequest_contract_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='workflow_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Datos del workflow'),
        ),
    ]
