# Generated by Django 4.2.7 on 2025-08-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_matchrequest_workflow_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='workflow_stage',
            field=models.IntegerField(default=1, help_text='1=Visita, 2=Documentos, 3=Contrato', verbose_name='Etapa del workflow'),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='workflow_status',
            field=models.CharField(default='pending', help_text='Estado específico dentro de la etapa', max_length=30, verbose_name='Estado del workflow'),
        ),
    ]
